### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#1]
Safari now support Web Extensions! Unfortunately, hardware wallet support will require some additional, perhaps native, work.

- [ ] Get the extension building for Safari
- [ ] Publish a dev build Safari users can install manually
- [ ] Package up a Safari extension for the app store (confirm licensing will work)

**Comment by 0xDaedalus** [comment]
Closed b/c stale and not on roadmap for next 12 months.
