### ISSUE TITLE
Tally doesn't pick up gnosis batch spends

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1030]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Version: b2fac99 (2022-02-22)

Received .1 ETH @ https://etherscan.io/address/0x5e42ab865602135339ed71b75baa3650f2c4fa8a#internaltx

### What did not work?

ETH balance displays as 0 and txn lists as 'dropped' inside Tally

<img width="371" alt="Screen Shot 2022-02-23 at 2 06 20 PM" src="https://user-images.githubusercontent.com/7005061/155391739-c60a82b7-3dff-46d4-a7e9-60ea0b63382c.png">

<img width="374" alt="Screen Shot 2022-02-23 at 2 06 25 PM" src="https://user-images.githubusercontent.com/7005061/155391741-1079722e-5f49-4e61-827d-be78a1e11bae.png">

**Comment by Shadowfiend** [comment]
Log would be super useful here! The dropped status is particularly interesting since it should only fire if there's an error submitting the transaction.

**Comment by Shadowfiend** [comment]
Oh wait was this not a transaction created inside tally? Even more interesting if so.

**Comment by 0xDaedalus** [comment]
Closed b/c stale and lack of logs
