### ISSUE TITLE
Unable to connect to yearn

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1033]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect Tally to yearn!

### What did not work?

When Tally is enabled as default wallet... I'm not able to connect with Tally; rather I get a notice re: mm

<img width="1331" alt="Screen Shot 2022-02-23 at 4 31 02 PM" src="https://user-images.githubusercontent.com/7005061/155411994-e1717b7f-07c5-4ca7-95e4-4ac3f4fd1650.png">

https://user-images.githubusercontent.com/7005061/155412004-12fdd36f-b116-4665-95a3-5d6496ec9214.mov

**Comment by Eastban120** [comment]
Same issue as @cairomassimo happening for me on Firefox (97.0.1 on MacOS 10.15.7): 
<img width="1312" alt="imagen" src="https://user-images.githubusercontent.com/68087535/156398278-414b4131-dd34-4380-8792-7d7f4ad77778.png">

**Comment by SJQuality** [comment]
Connecting with Yearn with no issues. But you do have to click "Show More" and then on Tally. Do we expect to be able to connect Tally to yearn via the MM option? @mr-michael

**Comment by 0xDaedalus** [comment]
This seems to be no longer an issue
