### ISSUE TITLE
Detect if Ledger is not ready

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1065]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Add another Ledger account

### What did not work?

I went through the process of adding ledger (a second time), but Ledger didn't have app selected.
This led to a congrats message, but address did not get added.

We need to detect that ledger is not set up properly and take users back to the first screen if that is the case.

### Version

Community Edition v0.11.2

**Comment by 0xDaedalus** [comment]
Closed b/c stale
