### ISSUE TITLE
Swap - Can't change From Asset

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1076]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Was trying to change the From asset when doing a swap. I was coming from a asset details page. 

<img width="362" alt="image" src="https://user-images.githubusercontent.com/80846886/156594493-9ba2b06f-f54e-4e56-9d99-5005d2c0bc2f.png">

### What did not work?

From: dropdown doesn't seem to act like a dropdown in this instance.
Works ok on other instances.
Very similar to a bug we previously had, now it seems contained to this use-case

### Version

Community Edition v0.12.0

### Relevant log output

```shell
Version: v0.12.0-25-gb11d448a (1 Mar 2022)
```

**Comment by 0xDaedalus** [comment]
This is no longer an issue
