### ISSUE TITLE
Add error message for sending w/o enough balance to pay gas

### ISSUE THREAD

**Issue by henryboldi** [tallyhowallet/extension#1083]
Currently just says,

<img width="241" alt="activity" src="https://user-images.githubusercontent.com/1918798/156661680-0a25d93d-3c8e-4dfb-8e1f-fbdb778aa440.png">

<img width="375" alt="scan" src="https://user-images.githubusercontent.com/1918798/156661696-660eaded-4870-4780-aa5a-7ceea405587d.png">

**Comment by VladUXUI** [comment]
Added myself first as we didn't cover this usecase yet.
The first thing we can do(that is a bit more immediate) Is to disable the send button and rename it to "Not enough funds" or something like that

**Comment by 0xDaedalus** [comment]
This is no longer an issue ✅
