### ISSUE TITLE
Swap - Sign-TX 

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1101]
Current issues that make it difficult to verify what you are signing:

- [x] #1224
- [x] USD value is missing the $ sign in front
- [ ] Advanced tab missing: Advanced tab should consist of as many details as we can offer (Decoded). We should at a minimum try and show Function Type and the contract you are interacting with. 
- [x] Gas should have USD value as well (covered in this ticket https://github.com/tallycash/extension/issues/957)
- [x] Raw Data tab 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/80846886/156914728-1e91b9ed-a209-48ff-9570-035695319487.png">

**Comment by Shadowfiend** [comment]
Things that should be doable this week:

- Raw data tab.
- $ in front of USD amounts.
- USD gas conversion (probably).

**Comment by jagodarybacka** [comment]
Raw data was added in #1134

**Comment by 0xDaedalus** [comment]
Closed b/c stale
