### ISSUE TITLE
Approve Asset Spend - Not always clear that adjusting gas price is possible.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#1140]
It is not immediately obvious that users can scroll down to adjust gas price when approving asset spend.

https://user-images.githubusercontent.com/94649004/157756473-3073d8bf-8d05-4ba8-b523-1543ae5994f1.mov

**Comment by kelvin0897** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
