### ISSUE TITLE
Swap Assets: Swap from doesn't provide any options

### ISSUE THREAD

**Issue by samajammin** [tallyhowallet/extension#1150]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Playing around with the swap feature, it's not listing any options. Searching for tokens also doesn't appear to do anything.

I'm guessing maybe this is because my wallet has 0 assets & 0 ETH. But there should be a more intuitive UI if that's the case. Even if I don't have balances, I would still like to be able to select tokens to view swap prices.

### What did not work?

https://user-images.githubusercontent.com/8097623/158038195-46503858-1b7f-4dbe-93f7-0ee189ef89a9.mp4

### Version

Community Edition v0.12.1

### Relevant log output

```shell
None
```

**Comment by samajammin** [comment]
Can confirm once I have ETH, it does display:
![Image 2022-03-12 at 3 13 52 PM](https://user-images.githubusercontent.com/8097623/158038249-51bfa1df-78e6-4c70-8332-7f21bb8d04ab.jpg)

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
