### ISSUE TITLE
Approve UX - limit to numbers only

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1155]
> If the user can only enter numbers, the input field should probably only allow numbers.

I leave to @VladUXUI to decide if we should fix it (and, in that case, we can open the issue)

_Originally posted by @cairomassimo in https://github.com/tallycash/extension/issues/1053#issuecomment-1066543556_

**Comment by 0xDaedalus** [comment]
Closed b/c stale
