### ISSUE TITLE
Token logos visible in Swap list but not on Assets page

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#1170]
Could there be a quick fix here?

https://user-images.githubusercontent.com/94649004/158485472-63446c7f-8381-4fc7-9945-b45a06629559.mov

**Comment by mhluongo** [comment]
We've been dancing around token list canonicalization for a bit. I think the quick fix is to reliably merge token metadata, regardless of the order the lists were fetched in.

**Comment by 0xDaedalus** [comment]
Captured in plenty of other issues
