### ISSUE TITLE
Read-Only: for any transactions

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1171]
This goes for swaps and send.

The send/approve/swap buttons should not be clickable in a read-only wallet.
The wallet should be disabled with the text "read-only wallet"

**Comment by Shadowfiend** [comment]
Not taking a position on the feature itself, but I'll state for the record that it is an intentional choice that we don't disable these flows for read-only accounts at the moment. Air gap wallets are a thing, and being able to go through the transaction flow for them is extremely useful.

**Comment by VladUXUI** [comment]
Humm, did not consider that. Atm they can't go through the flow, because the sign button is also disabled.
Maybe we need a bigger solve here, that would allow users to state if a wallet is an air gaped one. And handle those differently.

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
