### ISSUE TITLE
Account selection - Missing add address for Ledger

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1187]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect my second address from my Ledger

### What did not work?

Button is not there 

<img width="369" alt="image" src="https://user-images.githubusercontent.com/80846886/158795791-36b32965-a0d8-439b-a72c-06e7a49e096e.png">

### Relevant log output

```shell
Version: v0.12.2-1-g53105dba (16 Mar 2022)
```

**Comment by fernya** [comment]
I can think multiple levels of completion here:
1. Start the Ledger import flow regardless of connected Ledger status
2. Start the Ledger import flow, as above but signal the appropriate identification address somewhere
3. Start the Ledger import flow only if the appropriate Ledger is connected

**Comment by puppycodes** [comment]
Wont Fix: Not priority as of now
