### ISSUE TITLE
Ledger: Can't connect addresses from 2 different pages

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1218]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect Ledger

### What did not work?

I tried to connect more accounts from different pages (Page 1 and Page 2), but it only connected the addresses from Page 2

**To recreate:**
- Connect Ledger
- Select 2 addresses from page 1
- Go to page 2
- Select another 2 addresses and click connect.

In the wallet you will see only the last 2 addresses that were selected from page 2

### Version

Community Edition v0.12.2

**Comment by SJQuality** [comment]
Reproduced today.
