### ISSUE TITLE
Overview - Design clean-up

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1256]
Ticket from @mr-michael moved here

<img width="397" alt="Screen Shot 2022-03-26 at 2 12 02 PM" src="https://user-images.githubusercontent.com/7005061/160252520-36536ff4-aa5c-40c5-9468-2d1c8f699af8.png">

- "Addresses" -> "Accounts" (cc @VladUXUI ... let me know if you disagree here)
- Top-justify "Price" values so they are at the same height as "Balance" values (right now prices are in the the middle and the lack of alignment makes this difficult to read)
- Make "$" the same color as the dollar amount.

**Comment by VladUXUI** [comment]
Comment from @mr-michael :

@VladUXUI would it also be possible to perhaps apply some of the new 'earn' styling to this page?

e.g. the shadow and subtle gradient. the thicker separatation bar. whatever you think is best?

I know we want to overhaul this page soon after multi-network support is live! but tbh I'm anxious for us to give it a little bit more love in the meantime...it's just not keeping up visually with the dramatic improvements we've made to other parts of the wallet

<img width="186" alt="Screen Shot 2022-03-26 at 2 35 07 PM" src="https://user-images.githubusercontent.com/7005061/160252735-302a0944-2107-4c37-90aa-ed2fa633dad6.png">

**Comment by henryboldi** [comment]
> Make "$" the same color as the dollar amount.

😁

**Comment by VladUXUI** [comment]
Yes yes, i remember our debate. But let's not jump to making changes yet. Treat this as feedback

**Comment by 1saf** [comment]
With the price top aligned. The icon now looks out of place haha

**Comment by 1saf** [comment]
I feel like the spacing here
![image](https://user-images.githubusercontent.com/40786269/161057371-807027cc-09e5-41b0-bf1b-17476cd580a8.png)
Can also be cleaned up. Thoughts?

- Center the amount in the `<ShareAssetInput>` component.
- Increase and tighten the general spacing on the send page to make it look more even

**Comment by VladUXUI** [comment]
@1saf Heyo! thanks for the input and totally agree on the send page spacing! Above Asset/Amount should have more and between asset/amount and Send To should have less.

Quick note on this ticket though. It's meant as feedback and not really ready for dev. So this should go through a design phase first (that's on me) and after that through dev.

So treat anything tagged "design" as designers need to finish this first.

I'm sure we have some ui/ux fixes tickets out there, those are design ready and good to be knocked out.

**Comment by 1saf** [comment]
Ok yea no worries. In terms of design dev work @VladUXUI I'd love to be a part of it. I am a design dev after all hah

**Comment by henryboldi** [comment]
Can we close this? @mr-michael @VladUXUI
