### ISSUE TITLE
Asset Logo : Some funkiness going with correct logo disappearing

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1259]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Nothing

### What did not work?

Excuse the quality

![CleanShot 2022-03-28 at 11 39 57](https://user-images.githubusercontent.com/80846886/160360252-c8a60888-940d-4987-b450-622d75b2ad99.gif)

### Version

Community Edition v0.12.3

**Comment by 0xDaedalus** [comment]
This specific case is no longer an issue although token image flickering persists in other parts of the app
