### ISSUE TITLE
Add a 'locked' indication for when keyring is locked

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1313]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/961977614745092156

### What would you like to be able to do?

@VladUXUI @henryboldi 

We already discussed this briefly in Discord with Henry but it would be good if a user is able to see that the Keyring is locked and the wallet is in read only mode.

Since this is different from what people are used to it helps to clarify that the wallet is actually locked for transactions.

Maybe a small lock sign, or 'locked' somewhere at the top.

**Comment by 0xDaedalus** [comment]
This is complete ✅
