### ISSUE TITLE
Support Signing Legacy EIP-155 Transaction

### ISSUE THREAD

**Issue by 7alip** [tallyhowallet/extension#1315]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/963059201863720960

### What would you like to be able to do?

Because of not all the networks support EIP-1559, Tally needs to support legacy EIP-155 transaction type.

**Comment by mhluongo** [comment]
This works in `main`, though I don't think we should close it until the frontend shows non-EIP1559 gas controls as well.

**Comment by mhluongo** [comment]
Between this and derivation paths, we should have everything we need in the tech tree for RSK... except an Alchemy alternative!

**Comment by alepc253** [comment]
@mhluongo exactly, with those features RSK is ready to go. Thanks for taking this into account!
