### ISSUE TITLE
Standardize UI spacing

### ISSUE THREAD

**Issue by henryboldi** [tallyhowallet/extension#1318]
> I noticed that there are many inconsistence between the implementation and design and also non-standard and ad-hoc spacing usage. 
Do we have a plan to make a design component system which will make implementation more convenient?

– [rootial](https://github.com/rootial)

Good point! 🙇

I don't believe we've yet specified spacing in our design system. So there's two subtasks here:

- [ ] Define spacing conventions in our design system (@VladUXUI )
- [ ] Implement either a spacing component, spacing variables, or perhaps both

**Comment by VladUXUI** [comment]
That is true, our DS only states the 2 px grid and not vertical or horizontal spacing.
Our font line hight, button size, icon size, spacing it all revolves around the 2px grid. This means that we always have 2/4/8/16/24/32... and so on pixel spacing. Sometimes we also use 12 px and 0px, but rarely.

I don't foresee us adding a proper vertical and horizontal spacing pattern anytime soon (next 2/3 months), nor am i really confident atm that we could follow it, even if we did.

here is a screenshot from our in progress DS

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/80846886/163113450-2ca6b923-f775-4900-a83b-6f76b565534a.png">
