### ISSUE TITLE
Get re-listed on Firefox

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1346]
Decision: do we want this? 
- market share is ~10% 
- ledger needs to be reworked to work in firefox
- getting signed xpi and distributing it on the site is quite easy

Tasks:
- decouple UI and background dependencies
- #1335 
- [commit hash fix](https://github.com/tallycash/extension/pull/1343#issuecomment-1105231771)
- automated asset upload or .env with the environment variables
- turn off minification for firefox

**Comment by NukeManDan** [comment]
For sure, people want this :grin:

**Comment by waokdalf** [comment]
For sure, we need this

**Comment by puppycodes** [comment]
Wont Fix: Not priority until later
