### ISSUE TITLE
Selectively check token balances

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#136]
We should only waste resources checking token balances if a token...
1. Has a balance already, as reported by Alchemy
2. Has been manually added by the user as a custom token (not on a token list)
3. Is seen in a tx notification in the call chain, or in a tx in the past month (H/t @frankiebee )
4. Has had a balance in the past month, even if the balance is now 0
  * NB, I'm still a proponent for hiding 0-balance tokens in the UI after some time at 0 (eg 24 hours)

Due to how we track incoming ERC-20 transfers, we should be able to skip many periodic balance checks with some optimization. Unfortunately, balances can change due to transactions that didn't originate from our EOA wallet, eg because a token is rebasing, and that don't appear to be transfers "to" the wallet.

**Comment by 0xDaedalus** [comment]
Closed because we have an alternate solution here - namely:
- For alchemy-enabled chains - we rely on their proprietary `alchemy_getTokenBalances` method.
- For non alchemy-enabled chains - we rely on multicall - which has minimal resource overhead.
