### ISSUE TITLE
Swaps feature irresponsive in swaps until hitting refresh button

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1392]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Make a swap

### What did not work?

Wallet didn't calculate swap to quantity and couldn't set-up a transaction. 

Tried a couple of things that didn't do it:
- Switching accountS
- Adding an account

Hitting the refresh button did work. 

After this it also remembered my 'swap to' asset from previous attempts (KEEP), and already populated a swap to quantity without me actually selecting the asset.

Screen recording and logs below.

https://user-images.githubusercontent.com/71384922/166643857-24eb842b-d566-4459-bcd1-20bd6bd34f1b.mov

[logs_v0_13_2__2022-05-03T08_36_37+02_00.txt](https://github.com/tallycash/extension/files/8618690/logs_v0_13_2__2022-05-03T08_36_37%2B02_00.txt)

### Version

Community Edition v0.13.2

**Comment by 0xDaedalus** [comment]
@Naxsun could you please recreate this issue and re-post logs once https://github.com/tallycash/extension/pull/1417 lands?  There was a bug in our log exports that make debugging this very difficult which is fixed in #1417.

**Comment by Naxsun** [comment]
Yeah will do. I could also manually copy the logs from console if that helps.

I'll monitor now and then if the issue is occurring again.

**Comment by 0xDaedalus** [comment]
@SJQuality I could use your help reproducing this bug if you've ever encountered it or have any ideas on how we might reproduce it.

**Comment by SJQuality** [comment]
Yeah, I've not figured out how to repro it. I'll keep an eye on it.

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
