### ISSUE TITLE
Swap action execution button intermediate states

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1393]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Make a swap

### What did not work?

There's some intermediate states where the orange button on the bottom briefly shows an incorrect state.

- The button briefly has 'get final quote' before changing to  'waiting for approval transaction'
- The button briefly changes back to 'approve asset' after completion of the approval transaction

Screen recording below

https://user-images.githubusercontent.com/71384922/166644255-343add61-f625-492c-b7bb-f4cde17accb3.mov

### Version

Community Edition v0.13.2

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
