### ISSUE TITLE
Feature: support new RPC Method, wallet_switchNetworkRpcProvider

### ISSUE THREAD

**Issue by sambacha** [tallyhowallet/extension#1395]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/971583785135136819

## wallet_switchNetworkRpcProvider
The wallet_switchNetworkRpcProvider RPC method allows Ethereum applications (“dapps”) to request
that the wallet switches its active RPC Provider backend if the wallet has a concept thereof.

The caller MUST specify a chain ID. The caller MUST specify a valid URL for the RPC Endpoint

The wallet application may not arbitrarily refuse or accept the request.

[Link to the discussions thread on Ethereum Magicians](https://ethereum-magicians.org/t/eip-wallet-switchactiverpcprovider-rpc-method-for-supporting-aa-custom-rpc-methods-more/9142)

[Link to the draft RPC Spec](https://github.com/manifoldfinance/wallet_switchNetworkRpcProvider)

Input, feedback, etc is more than welcome! This is a *draft* spec, meaning it is not final.

**Comment by 0xDaedalus** [comment]
Closing b/c it seems like there has not been much progress on moving this spec forward since August
