### ISSUE TITLE
Utilise advanced BlockNative gas esimations for mainnet

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#1397]
# Context
BlockNative gives us an estimation of gas prices for the next 5 blocks but we are not using that information anywhere. 
* [BN gas fee post](https://www.blocknative.com/blog/base-fee-prediction-and-intelligent-max-fee)
* [BN gas api example](https://docs.blocknative.com/gas-platform#example-response-payload) 

In the [makeBlockEstimate](https://github.com/tallycash/extension/blob/b46acbe068a818f1e3d3a09f126bed48716ac200/background/redux-slices/transaction-construction.ts#L122) we use only the first element with the confidence that we are looking for. It's practical because it's the price of the next block, but [we also have the estimation already there for the next 5 blocks](https://github.com/tallycash/extension/blob/10d3c387f8c9c6d05ee57fa0e416dd2fdcfbe18f/background/third-party-data/blocknative/index.ts#L94)

- The solution would use the estimates for the next 3 blocks. (These are virtually error-free based on the bn articles)
- The lookup would happen based on the current block height.
- The changes in the gas fee would be represented in the UI + some animation to make it easier to understand
- The polling period for gas fetch should be 30s 

# Value of the proposal

In highly volatile market conditions the base gas fee could change quite a bit, and this would help us to always show our most informed guess for the gas fee without spamming the Blocknative api. 

# Priority

Most of the time our current gas estimation is good enough, so this is a nice to have feature.

**Comment by henryboldi** [comment]
I don't believe we need to do this for solving the high network fee estimations 80%-90% of the way! We'll see.

**Comment by 0xDaedalus** [comment]
This has been completed ✅
