### ISSUE TITLE
Tally NOT set as Default- popup message and we still come up

### ISSUE THREAD

**Issue by SJQuality** [tallyhowallet/extension#1438]
### **Build Info:**
Release build 0.13.4 - Chrome

### **Related Ticket/PR**
https://github.com/tallycash/extension/pull/1431

### **Reproduction Steps:**

1. Have Tally set to default OFF
2. Connect to Uniswap

### **Expected Result:**
If we are Not set as default are we supposed to pop-up?
no additional messages from Tally

### **Actual Result:**
We create a pop-up windows with a message about there not being an account. 

https://www.awesomescreenshot.com/video/8874279?key=ef57b725a3c6d0f7854651460451acb2

**Comment by SJQuality** [comment]
This may actually be a Uniswap issue, or something we are doing that confuses Uniswap. 
If Tally is set as Default, then when you connect a wallet, you get the "Injected" option
If Tally is NOT set as Default, then you get a list of wallets with MM and others. 

Sometimes, Uniswap gets in this weird state where Tally is NOT set as default, but "Injected" is displayed instead of the wallet options. (See video above)

**Comment by 0xDaedalus** [comment]
No longer an issue
