### ISSUE TITLE
Undesirable Autofill Behavior

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#1443]
We get an ugly white background when selecting an address from the autofill menu.  Do we want to fix this to match our apps styling or just disable autofill?

Version 0.13.4.

https://user-images.githubusercontent.com/94649004/168381957-92e7d0ef-57bc-4572-9c82-fc564a7153a7.mov

**Comment by mhluongo** [comment]
I think we disable auto-fill initially, then replace this with a custom completion control based on the address book?

**Comment by Shadowfiend** [comment]
IMO disabling autofill is a user hostile move  if we don't have a good replacement.

**Comment by mhluongo** [comment]
I think I get where you're coming from, but auto-filling addresses in a wallet extension without context is making phishing and other mistakes much, much easier.

**Comment by Shadowfiend** [comment]
Hmm... What kind of scenarios are you thinking of here?

**Comment by mhluongo** [comment]
Any time we show a list of addresses without context or history we enable mistakes, yeah?

One might be: I convince you to send a small legitimate amount to an address that looks just like yours, perhaps for a service. Then in the auto-fill a user is like "oh, that's my address" and accidentally misfunds a large amount

**Comment by Shadowfiend** [comment]
Sure, but anytime you require someone to put in an address wholesale without help the same is true. It's not clear to me the one is strictly worse than the other, tbh.
