### ISSUE TITLE
UX suggestion - Snack bar - add link to view txn?

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1453]
@VladUXUI what do you think about updating our current "Transaction signed, broadcasting..." modal to:  "Transaction signed, broadcasting... **View**"  and the "View" button takes you to activity so you can see if it gets confirmed?

https://user-images.githubusercontent.com/7005061/160731245-b1664289-cefd-4363-9db3-1e02fe96f658.mov

<img width="458" alt="Screen Shot 2022-03-29 at 9 11 16 PM" src="https://user-images.githubusercontent.com/7005061/160731250-d0c02006-492b-4f38-ae3c-7026f088ed01.png">

**Comment by 0xDaedalus** [comment]
Closed b/c stale
