### ISSUE TITLE
Add validation for token decimals in `SharedInput`

### ISSUE THREAD

**Issue by henryboldi** [tallyhowallet/extension#1465]
I tried depositing into USDT. If there's too many decimals for USDT I'm hitting this error,
<img width="1000" alt="error7" src="https://user-images.githubusercontent.com/1918798/160462479-5ee84221-aca7-4508-892f-fa858492be0a.png">

Try 7.8916487 → Error
Try 7.891648 → Works

In the UI it gets stuck on a blank screen.

Approving this and making a new ticket to update `SharedInput`'s validation.

_Originally posted by @henryboldi in https://github.com/tallycash/tally-extension-token/pull/88#pullrequestreview-923578093_

**Comment by 0xDaedalus** [comment]
This seems to be `earn` related - closing
