### ISSUE TITLE
Earn - Implement Pool 2 in extension

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1471]
- [ ] special pool item on the list for DOGGO/ETH pool
- [ ] change "Vault" badge to "LP Pool"
- [ ] change Rewards to "DOGGO"
- [ ] change pool info accordion's content
- [ ] change estimated APR accordion's content
- [ ] show Pool 2 based on contracts state
- [ ] Cards status changes [figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=9489%3A129239)

<img width="345" alt="image" src="https://user-images.githubusercontent.com/20949277/170240175-d715f203-c385-4999-af5e-aa671a2875bf.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/20949277/170240237-ddab6b73-acf8-4026-a91b-c43b9e63f86f.png">

**Comment by jagodarybacka** [comment]
@mhluongo for sure UI is not fully implemented

**Comment by jagodarybacka** [comment]
Removing "needs work breakdown" label as it seems like we know what to do.

**Comment by puppycodes** [comment]
Wont Fix: earn related stuff not relevant for now
