### ISSUE TITLE
Manifesto  - Improve design/hierarchy 

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#1475]
Needs a bit more work. At first i didn't realise that first line is a title (both now, and when designing)

Although Henry was right to changed the font size of the manifesto secondary titles, still doesn't feel enough.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/80846886/162405993-c4d6f729-4e4d-4185-8815-86b2730d7795.png">

**Comment by 0xDaedalus** [comment]
Closed b/c related to claim and will be revisited shortly
