### ISSUE TITLE
Duplicate assets showing up in swap menu.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#1480]
Version: 76124477405ed6cc3ffcce3456f3d242f001c61f

<img width="382" alt="image" src="https://user-images.githubusercontent.com/94649004/168640485-51d7337f-db02-4f03-83d5-b7b41d4a759c.png">

**Comment by jagodarybacka** [comment]
So I've made a little research and I'm not sure how we want to handle this issue. Items with the same token symbol are similar but they have different contract addresses:
![image](https://user-images.githubusercontent.com/20949277/169533610-7a4dd96f-58e1-4865-8abb-cc617f04619b.png)

**Comment by greg-nagy** [comment]
Are they both in one of our token lists? 

We have a [similarity score here](https://github.com/tallycash/extension/blob/562321de3280e6f9115159c898888530bcd6a0e3/background/lib/asset-similarity.ts#L14) but the different addresses are scary for this level of similarity.

**Comment by jagodarybacka** [comment]
@greg-nagy If I remember correctly they were all coming from the same place.

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
