### ISSUE TITLE
Remove account warning message not appropriate for Read-only accounts.

### ISSUE THREAD

**Issue by SJQuality** [tallyhowallet/extension#1493]
### **Build Info:**

Release 0.13.4

### **Reproduction Steps:**

1. Add Read-only Account
2. Remove Read-only Account

### **Expected Result:**
???? Some simple confirmation? - Product question @VladUXUI @mr-michael 

### **Actual Result:**
![image](https://user-images.githubusercontent.com/103908695/169108174-e09662f2-2988-4b4a-84e5-ab43cd21a3c1.png)

**Comment by 0xDaedalus** [comment]
No longer an issue
