### ISSUE TITLE
Sleepy Ledger = Endless Swap loop

### ISSUE THREAD

**Issue by SJQuality** [tallyhowallet/extension#1526]
### **Build Info:**
Main Build #3197

### **Reproduction Steps:**

1. Have wallet connected to Ledger
2. Let Ledger go to sleep
3. Attempt Swap

### **Expected Result:**
We should detect that the Ledger is asleep, or needs unlocked.. or something

### **Actual Result:**
Endless swap loop

https://www.awesomescreenshot.com/video/9098406?key=e3a8ce1f053d3a1d56a131e4b3137497

**Comment by SJQuality** [comment]
This can also just cause TH to just close and reset to the Swap/Tx page

**Comment by 0xDaedalus** [comment]
Stale
