### ISSUE TITLE
Sleepy Ledger - Send - not working

### ISSUE THREAD

**Issue by SJQuality** [tallyhowallet/extension#1533]
### **Build Info:**

v0.13.7 Build #3209

### **Related Ticket/PR**

https://github.com/tallycash/extension/pull/1525

### **Reproduction Steps:**

1.  Have sleepy Ledger (not pointed out in video) 
2. Send a token from Ledger account (see Vid)

### **Expected Result:**
Some sort of notification to wake up Ledger and enter PIN?

### **Actual Result:**
Flash Ledger screen and transaction is skipped. 

See Video

https://www.awesomescreenshot.com/video/9118941?key=870c14bff7f4626e29facf809cbb94b1

**Comment by SJQuality** [comment]
Maybe related to https://github.com/tallycash/extension/issues/1526

**Comment by 0xDaedalus** [comment]
Stale
