### ISSUE TITLE
mainnet fork on uniswap 

### ISSUE THREAD

**Issue by dingchaoz** [tallyhowallet/extension#1635]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/986794200827830334

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Replicate the 2022 EthDenver [demo](https://drive.google.com/drive/u/0/folders/1c2jPRuqPI-wUVgeYJsWebQ_IdTvMtwnG) of using Tally on a mainnet fork performing Uniswap swap, following on this[ pull request](https://github.com/tallycash/extension/pull/1094) 

### What did not work?

Wasn't able to 
1. see 10000ETH funds deposited into the test wallet 
![image](https://user-images.githubusercontent.com/10751336/173983615-fe2531fb-aa93-4f00-badd-0ccba191278c.png)

2. connect Tally wallet on local forked mainnet and perform a swap, seems like only connected to Ethereuem mainnet 
![image](https://user-images.githubusercontent.com/10751336/173983643-0b19b4b1-3d1f-4344-908b-df13626dcf13.png)

I am able to run the forked chain locally and run the `yarn start` fine, and load Tally wallet from local pack

**Comment by greg-nagy** [comment]
We have updated our app a bit since then and you need to enable it in the [.env files](https://github.com/tallycash/extension/blob/4ab73c55feec54dc995f338a0cdd8d80269d3f19/.env.defaults#L13-L14)
You can do that by either editing `.env.defaults` or creating a `.env` and put the values there. 
The url in your case will be `https://127.0.0.1:8545/`

Another important thing is that you need to see this at the end of `yarn install`
![CleanShot 2022-06-16 at 11 05 03](https://user-images.githubusercontent.com/7690112/174035027-a2b10dc6-0782-45d8-bdd1-de487507c7b4.png)

**Comment by dingchaoz** [comment]
Thank you for looking into it, after adding .env still see the same 0 Eth balance and wrong network when using Uniswap, could you check if anything else I may missed? 

1. Added localhost url and enabled .env
![image](https://user-images.githubusercontent.com/10751336/174066240-66e61d77-46a0-437f-b41f-1e4aaf71adb7.png)
2. yarn install finished fine
![image](https://user-images.githubusercontent.com/10751336/174066526-9ef8182e-6f81-4c93-b2a2-0275165fd4b6.png)
3. Start running mainnet fork, and yarn start 
![image](https://user-images.githubusercontent.com/10751336/174066572-c4313391-586e-4c2e-af22-de18067ffd64.png)
4. Load unpacked in brave extension, set up a new wallet using the same seed phrase recommended
5. The first wallet `0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266` shows balance of 0 Eth, though the local mainnet fork shows it should have 10k ETH
<img width="376" alt="image" src="https://user-images.githubusercontent.com/10751336/174066788-79748dfb-ab99-4855-b6fa-0534ff8b4eaa.png">
![image](https://user-images.githubusercontent.com/10751336/174066817-61fe8931-047a-4a44-a24c-990e924ae65c.png)
6. When connect to uniswap, it shows `wrong network` 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/10751336/174066888-7f171e7d-4081-4e4c-8f55-e41bd68ea2a9.png">

**Comment by greg-nagy** [comment]
![CleanShot 2022-06-16 at 15 12 31](https://user-images.githubusercontent.com/7690112/174077474-d6283d67-622c-4db4-b527-b6065c6f9b4c.png)

this is sus :)

**Comment by dingchaoz** [comment]
Changed it to true, restarted the socket server and reloaded wallet, this time the balance seems pending to be loaded for long, and couldn't perform swap still on uniswap, anything i may have missed? 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/10751336/174101398-90d76471-9947-409b-90b2-5c4d1f706600.png">

**Comment by dingchaoz** [comment]
Not sure if this is relevant to the issue, found in errors connecting to the mainnet forked provider 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/10751336/174102411-a468f1bf-9706-4593-be5e-adde7509bc0e.png">

**Comment by greg-nagy** [comment]
not sure :( I haven't tested this functionality since Denver :(

the last time I used it, the account updated and could perform a swap on uniswap (it was flaky though)

**Comment by dingchaoz** [comment]
Could you share the original tally code you used for demo in Denver if possible? The PR seem were merged and I wonder there other changes might have impacted the functionality..

**Comment by greg-nagy** [comment]
All I have is in this git repo

**Comment by 0xDaedalus** [comment]
Stale
