### ISSUE TITLE
Swap - Loading state for amount

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#1638]
On swaps page we refresh the quote quite often and it results in a jittering UI 

It would be good, to have decent loading state for this component.

https://user-images.githubusercontent.com/94649004/173900397-7a6b138f-4537-43ad-b6d6-f195944a511b.mov

See: https://github.com/tallycash/extension/pull/1626#pullrequestreview-1007959029

**Comment by 0xDaedalus** [comment]
No longer an issue
