### ISSUE TITLE
In-page JS and dApp API design

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#168]
We have different design needs for the in-page JS API we offer dApp developers. We need an API that's backwards-compatible to the [January 2021 changes in MM](https://docs.metamask.io/guide/provider-migration.html#table-of-contents), but that's more flexible for our use case.

- [x] Optional ability to override an already installed MetaMask provider for interop (let MM include provider, Tally does the signing) 
- [ ] Expose additional chain providers simultaneously (eg [`window.solana`](https://docs.phantom.app/integrating/detecting-the-provider))
- [ ] Consider exposing `window.tally` with all supported network providers, rather than unnecessarily polluting the `window` object.
- [x] We need to be able  to support users seeing a "use Tally as the default Web3 wallet?" dialog on dApp page load.

**Comment by 0xDaedalus** [comment]
Closed b/c we do not plan to support non evm chains in the next 12 months - and we would have to move away from our `Proxy` pattern as well as MM impersonation if we want to avoid polluting the `window` object.
