### ISSUE TITLE
Multiple 'connect to dapp windows open simultaneously

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1741]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Test behavior around dapp connections

### What did not work?

When closing the extension view while on the dapp connection page, re-opening the extension opens it up on the normal wallet page (overview, wallet, swap or menu), however the dapp connection page screen is still open, and can be re-opened. 

When doing this multiple times, there's multiple extension views. These extension views do not open when you open the extension by clicking the icon, but on a mac can be opened from the 'all open window view'.

'Close' the extension while in this view
<img width="1279" alt="Screen Shot 2022-07-06 at 13 38 20" src="https://user-images.githubusercontent.com/71384922/177543441-197d2ffb-3fab-44f1-85ea-4998deec1c25.png">

Doing this multiple times leads to multiple open windows
<img width="334" alt="Screen Shot 2022-07-06 at 13 40 42" src="https://user-images.githubusercontent.com/71384922/177544090-722912d0-1622-443a-b7c9-261425e8de8d.png">

My personal 1st intuition was this to be confusing, but needs to be discussed on a broader product level.

### Version

Community Edition v0.13.13

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
