### ISSUE TITLE
Include the "display asset" across the Redux store

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#176]
Instead of `displayAmount`, `userAmount`, or `formattedAmount` fields by themselves, make sure the Redux store always contains enough data to go backward for any currency conversions.

For example, a user balance in ETH might be...

```
{
   amount: 12345n,
   asset: { name: "Ether", ... },
   displayAmount: 100n,
   displayAsset: { symbol: "USD", decimals: 2, ... }
}
```

**Comment by 0xDaedalus** [comment]
Closed because it seems that the referenced fields are no longer present in the codebase.
