### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [tallyhowallet/extension#1776]
### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

Translate the wallet without getting into licensing issues

### What did not work?

The licensing

### Relevant log output

```shell
GPLv3-only in https://hosted.weblate.org/projects/tallycash/wallet/#information

but

https://github.com/tallycash/extension/blob/bd61cfda0955a1b43e25e0b783e7de27abe2e615/LICENSE-additional-terms.txt#L19

can be changed in 
https://hosted.weblate.org/settings/tallycash/wallet
and
https://hosted.weblate.org/settings/tallycash/glossary

The former should not be marked as a glossary btw.
```

**Comment by Shadowfiend** [comment]
Hope we can do this without a SPDX license identifier as I don't believe there's a good identifier for the DAO exception here.

**Comment by comradekingu** [comment]
If you mean for Weblate, just mention the DAO exception in the info field.
My main point was to include the "or later", as opposed to "GPLv3-only", so as not to make translations incompatible.

**Comment by jagodarybacka** [comment]
@gasolin can you please take a look at this issue?

**Comment by 0xDaedalus** [comment]
Closed because stale

**Comment by comradekingu** [comment]
@Naxsun @jagodarybacka @gasolin 
Still "The full process is still under construction", and the project is locked on Weblate.
If one of you add "kingu" in https://hosted.weblate.org/access/tallycash/#users I can fix it.
