### ISSUE TITLE
On ERC-20 contract interaction, add token to tracking

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#181]
Any time `balanceOf(account)`, `transfer`, or `transferFrom` is called on a contract, that contract should be added to token tracking.

Because we don't want to check every token contract in the world, we need heuristics like this.

**Comment by 0xDaedalus** [comment]
Closed b/c a similar (although not as extensive) solution has been achieved in https://github.com/tallyhowallet/extension/pull/1840
