### ISSUE TITLE
Visual - Gas settings text jumped

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1819]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Change gas settings

### What did not work?

Works, just a minor jump of the text for 'Express' --> 'miner & max base'

Version: 0.13.13_0dc5dff

<img width="366" alt="Screen Shot 2022-07-14 at 08 51 03" src="https://user-images.githubusercontent.com/71384922/178920151-61f9011f-ca14-40de-8da7-3e57ef7b0ac9.png">

### Version

Community Edition v0.13.13

**Comment by henryboldi** [comment]
Basically align by the labels (max base, miner) rather than aligning right, correct?
<img width="366" alt="178920151-61f9011f-ca14-40de-8da7-3e57ef7b0ac9" src="https://user-images.githubusercontent.com/1918798/178920764-436f213a-5906-4cd3-ba37-8f18fe0cfbf0.png">

**Comment by Naxsun** [comment]
Yeah I think that would do it!
