### ISSUE TITLE
Don't change network for dApps when the network is changed for the extension

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#1846]
* https://matrix.to/#/!WZRftnsYNnOtzOGuZy:thesis.co/$AO0U9C2IkgGRwR4m0Q8bX4K5B_LstdurVxbJi9cSR2k?via=thesis.co&via=matrix.org 
* https://github.com/tallycash/extension/blob/c934f88f075b0ca71de889923d02db193549902f/background/services/provider-bridge/index.ts#L268 

⚠️ My original assessment was wrong! For the real reason see https://github.com/tallycash/extension/pull/1963#issuecomment-1217990405 ⚠️

**Comment by greg-nagy** [comment]
The real source of the problem can be found in this comment:

https://github.com/tallycash/extension/pull/1963#issuecomment-1217990405

thanks @mhluongo for the helpful debug session

**Comment by 0xDaedalus** [comment]
This is complete ✅
