### ISSUE TITLE
Error on adding the same Ledger twice

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#1851]
![Screenshot from 2022-07-26 15-51-14](https://user-images.githubusercontent.com/427505/181099817-17afd43e-6960-4ecc-9ef8-bf4ca26c536c.png)

I got this error testing

1. I added a Ledger with account A on Ethereum
2. I rebuilt the extension with this PR to test the migration
3. I refreshed the extension, and everything looked good
4. I added the same Ledger with account A on Polygon

Everything looked good, but wanted to report the above as it looks like a deeper backend issue around cross-chain Ledger stuff.

_Originally posted by @mhluongo in https://github.com/tallycash/extension/issues/1839#issuecomment-1195914625_

**Comment by 0xDaedalus** [comment]
Stale
