### ISSUE TITLE
Web3modal dapps don't update Logo & Name

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1859]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to a dapp using web3modal 

### What did not work?

The connection works, Tally Ho still pops up and connects. 

The name and logo isn't showing anymore though. When installing an older revision, 0.13.3, the logo and name still load. Examples on fei.money and https://app.klimadao.finance

<img width="1483" alt="Screen Shot 2022-07-28 at 14 01 41" src="https://user-images.githubusercontent.com/71384922/181500351-75412b09-ea0c-41ad-9fcb-8d9ccc38a745.png">
<img width="1491" alt="Screen Shot 2022-07-28 at 14 03 09" src="https://user-images.githubusercontent.com/71384922/181500403-cf973f09-9964-44ea-a8b2-617810f20546.png">

### Version

Community Edition v0.14.1

**Comment by 0xzoz** [comment]
This is an issue with web3modal and using `window.web3` as a fallback option. This [PR](https://github.com/WalletConnect/web3modal/pull/571) addresses the issue.

**Comment by herbig** [comment]
@0xzoz I had thought there was some web3modal configuration to have the Tally logo appear.

It should just appear by default if that PR is merged? With no further web3modal adjustments?

**Comment by 0xDaedalus** [comment]
Stale
