### ISSUE TITLE
No sign button on Gnosis Safe - HWW transaction

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1860]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Sign a transaction of a Gnosis Safe

### What did not work?

Wanted to sign a Gnosis Safe transaction on Ethereum mainnet. Connected by Ledger through Tally. The extension itself was on Polygon, but was connected to Gnosis Safe on mainnet. 

There wasn't an option to approve the transaction in the extension. The button is missing.

I think the extension was expecting a Polygon transaction. After changing the extension to Ethereum, could sign the transaction without issues.

![image](https://user-images.githubusercontent.com/71384922/181503275-8a597947-a253-4048-8e79-0058bf83848e.png)

### Version

Community Edition v0.14.1

**Comment by 0xDaedalus** [comment]
Stale
