### ISSUE TITLE
NFT viewing - only displays first 99 NFT's in wallet

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#1867]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View NFT's (read only account)

### What did not work?

Version: https://github.com/tallycash/extension/actions?query=branch%3ANFT-view-QA

Only the first 99 NFT's are displayed, this wallet has more.

Also the images of most of the 99 NFT's aren't loading but maybe that's because these's are not available. A differentiator between 'loading' and 'not available' images could be helpful, and if possible have an option to filter out the not available ones

<img width="353" alt="Screen Shot 2022-08-01 at 15 20 09" src="https://user-images.githubusercontent.com/71384922/182157198-09c980a8-69c3-4ac5-951d-cdc0c97e6c7b.png">

### Version

Community Edition v0.14.1

**Comment by henryboldi** [comment]
For the first version I believe we're ok with chopping it off at ~100. @greg-nagy, correct?

**Comment by greg-nagy** [comment]
> For the first version I believe we're ok with chopping it off at ~100. @greg-nagy, correct?

Yes! 

There are multiple loading states in the plans that are different from the empty state and also the pagination issue. But for initial release I think it will be ok — or we will get push back for the QA build.

**Comment by 0xDaedalus** [comment]
No longer an issue
