### ISSUE TITLE
MATIC is not treated as a base asset

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#1881]
Using [`isNetworkBaseAsset()`](https://github.com/tallycash/extension/blob/hide-max-for-base-asset/background/redux-slices/utils/asset-utils.ts#L52) is not working on Polygon because MATIC is not treated as a base asset by this function.  [This comment](https://github.com/tallycash/extension/blob/hide-max-for-base-asset/ui/pages/Swap.tsx#L104-L105) is probably referring to the same problem. 

Issue base on this comment https://github.com/tallycash/extension/pull/1880#discussion_r936714144_

**Comment by mhluongo** [comment]
Hmm, I thought we had resolved this cc @0xDaedalus

**Comment by 0xDaedalus** [comment]
This is now resolved ✅
