### ISSUE TITLE
Manual seed phrase retrieve tooling

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#1905]
Discord convo: 
https://discord.com/channels/808358975287722045/1002635259797573662

Element convo: 
https://matrix.to/#/!qBkFvIWWooAZQzbfHb:thesis.co/$puhLqeVk9NwL8pMl_4qgeVQO4lB5dBkgtPjyKwPYSWQ?via=thesis.co&via=matrix.org

Feature pitch: 
Implement a [solution similar to what MM has](https://metamask.zendesk.com/hc/en-us/articles/360018766351-How-to-recover-your-Secret-Recovery-Phrase) to retrieve seed phrase from keychain

- grab the keychain from local storage through console 
- provide a tool to decrypt it with the password and retrieve the seed phrase in plain text (preferable to have it as a CLI tool, to make phising harder, but webapp also can work if it's on a verifiable location)

**Comment by 0xDaedalus** [comment]
Stale
