### ISSUE TITLE
Swap: Token not available in Token List will show insufficient Balance even if it is the one resulting token of the exchange

### ISSUE THREAD

**Issue by ramaruro** [tallyhowallet/extension#1944]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I am trying to consolidate some "dust" coins (i.e. small amount) into other dust coins using the Tally Swap Feature, for example ALCX to LDO.

### What did not work?

If the "Swap to" coin is not in the token List, the resulting amount of the swap will have a number and it will say "Insufficient Balance"

This is very confusing, as the Destination Coin should not have ever an "Insufficient Balance", unless the swap itself is impossible (i.e. not enough liquidity in LP Pools). 
If this swap is not possible, the message needs to be different, if it is possible, there should be no "Insufficient Balance" message popping up.

The example below shows this for LDO as the "Swap To" coin. LDO is not in available in the Token List.
![image](https://user-images.githubusercontent.com/68167410/184516262-57df7114-d07f-478a-bb09-6069fefaaafc.png)

### Version

Community Edition v0.14.3

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
