### ISSUE TITLE
Swap: Token not available in "Swap To" token List can be accessed by reverting swap from a "Swap to" coin available in wallet

### ISSUE THREAD

**Issue by ramaruro** [tallyhowallet/extension#1945]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I'm trying to swap and consolidate some dust tokens (small amounts) in my wallet. 

The "Swap To" coin is not in the token list but in my wallet.

### What did not work?

If the "Swap to" destination token is not available in the token list but you have it in your wallet, you can access it by starting as a "Swap From" coin and reverting the Swap.

This is a workaround, but cumbersome.

The "Swap To" token list should be expanded to allow for entering a Token Address (as Matcha does), as the Token Lists will never be complete.
Also, the token lists should incorporate some common sanitized list available (e.g. from Uniswap)

**Comment by Shadowfiend** [comment]
Uniswap is already included in our overall list I believe. It sounds like #1846 covers the rest of this issue? Feels like we can consolidate if so.

**Comment by mhluongo** [comment]
Pretty sure 1846 isn't the issue you were looking to reference @Shadowfiend
