### ISSUE TITLE
Add filter to Wallet Overview: choose which Assets should show and/or show by groups, e.g." Readme only" Addresses, active Addresses

### ISSUE THREAD

**Issue by ramaruro** [tallyhowallet/extension#1953]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/1008545252778463232

### What would you like to be able to do?

The main page of the Wallet shows all assets for all addresses on all networks.
I understand this is a feature and it is a nice summary view.
But it can lead to confusion when merged with Watched (Read Only) addresses.

Right now this Summary includes everything from Live and Ready-Only addresses.

Some options to improve this:
* Add a filter to decide what to display
* Display by groups, defined in the Filter or Settings
 
![image](https://user-images.githubusercontent.com/68167410/184541936-e5dc3d38-7378-48f7-b4aa-88a861bd4096.png)

**Comment by 0xDaedalus** [comment]
Stale
