### ISSUE TITLE
Unlock wallet for tx - cancel and back buttons are not working

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2008]
### Steps to reproduce
1. Attempt SIWE with wallet locked
2. Wallet is asking for a password on a popup window

*Current*: "Back" and "Cancel tx" buttons are not doing anything
*Expected*: Back button doesn't really make sense because there is no place to go back to, Cancel tx should reject tx and close the window

![image](https://user-images.githubusercontent.com/20949277/186173598-1ae38d0b-0a7f-4963-be6e-e8423577f6c2.png)

**Comment by Shadowfiend** [comment]
This should get fixed with the updates signing flow fwiw. Up to y'all if you want to fix it on the old one in the meantime.

**Comment by kkosiorowska** [comment]
I think we can close this task.  The ,,Back'' button has been removed. The part related to the ,,Cancel'' button has also been resolved. Check this [commit](https://github.com/tallyhowallet/extension/commit/253e0e6e997cc76e2662f8ee6517a23f8414e30e).
