### ISSUE TITLE
The cpu is very high, nearly 20% plus after install tallycash!

### ISSUE THREAD

**Issue by jerryhe666** [tallyhowallet/extension#2020]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Both under chrome and edge browser, the cpu is very high, nearly 20% plus after install tallycash!
I use MAC OS.

### What did not work?

Make other app does work! After turn it off ,everything return to normal.

**Comment by mhluongo** [comment]
@jerryhe666 are you still experiencing this in the latest version from the Chrome store (`v0.15.1`)?

**Comment by 0xDaedalus** [comment]
Stale
