### ISSUE TITLE
Phrase verification - additional word options with 8 words filled in

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2027]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

User tried to set-up a new wallet.

### What did not work?
NOTE: browser type unconfirmed, I selected Chrome to be able to ticket. Will try to confirm with the user

<img width="767" alt="Screen Shot 2022-08-26 at 08 59 41" src="https://user-images.githubusercontent.com/71384922/186842277-57e084d5-16d8-4856-a491-6c08006d72f0.png">

### Version

Community Edition v0.14.5

**Comment by 0xDaedalus** [comment]
No longer an issue
