### ISSUE TITLE
Massive lag when interacting with the wallet

### ISSUE THREAD

**Issue by puppycodes** [tallyhowallet/extension#2033]
- [x] https://github.com/tallycash/extension/issues/2036
- [ ] Rework transaction enrichment so it does not block downstream user-facing functionality.

**Comment by mhluongo** [comment]
> Rework transaction enrichment so it does not block downstream user-facing functionality.

I think we can break this into two parts

1. The UI shouldn't wait on enrichment — there are pre-enrichment events already
2. Enrichment should be broken into phases so transactions and addresses can be 

The first feels easy, the second feels necessary but heavy... and needs something like [proper queueing](https://github.com/tallycash/extension/issues/2036#issuecomment-1229231037)
