### ISSUE TITLE
"Scale up" or "scale down" address monitoring based on extension state

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#2048]
- [ ] If the extension popup and all tabs are closed for more than 10 minutes, we don't need to do price checks more than once every 6 hours
- [ ] If the extension popup and all tabs are closed for more than 10 minutes, we don't need to poll recent asset transfers more than once every 5 minutes
- [ ] If a network is tracked, but hasn't been viewed for more than a day....?

@Shadowfiend @0xDaedalus other ideas here? If we can get a longer list, there should be a clear paradigm that we can use across a few polling-related performance and resource issues.

**Comment by 0xDaedalus** [comment]
Complete
