### ISSUE TITLE
Unknown max fee/gas on most recent activities

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2079]
Fix unknown max fee/gas field in recent activities
![image](https://user-images.githubusercontent.com/20949277/187460593-8bde6b61-a0f5-4a93-8d6d-08849f7ea21a.png)

**Comment by kkosiorowska** [comment]
I have looked at several activities and I don't see this issue. @jagodarybacka Could you check if the issue still exists? If not let's close it. If yes, let's describe the conditions under which the issue occurs.

**Comment by jagodarybacka** [comment]
Yeah, seems to be fixed now
