### ISSUE TITLE
The create new wallet interface closes whenever it loses focus

### ISSUE THREAD

**Issue by Erotemic** [tallyhowallet/extension#2103]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

In chrome, I installed the extension, clicked it, went through prompts to create a new wallet. I got as far as "write down your secret phrase".

### What did not work?

Whenever I did anything that removed focus from the chrome window the tally-ho UI disappeared and I had to start again.

This first happened when it asked me for a password. I went to a terminal to use diceware to generate a password. When I clicked on the browser (Chrome Version 105.0.5195.52 (Official Build) (64-bit) on Ubuntu 22.04) to put in that password the tallyho popup just closed. 

I went through the dialogs again and still had the password in my buffer, so I copy/pasted it and continued. It then had me write down my secret phrase. I went to copy it into a text file, and that worked fine, but again when I came back to chrome, the popup went away, and I had to start the process again. Interestingly it skipped the password step, so that went through, but it asked me to copy down the phrase again, but this time it was a different phrase. I went through this cycle 3 times.

Notably, I did just not paste it into a text buffer one time, but because the phrase changes each time I wasn't able to validate that I had the correct phrase because if I left chrome to actually paste it and look at it, then tallyho would close.

### Version

v0.15.0

**Comment by mhluongo** [comment]
Thanks for the report @Erotemic! I've been working on an alternative tab-based onboarding flow that should cover this — the current behavior is difficulty to avoid in the extension pop-up.

cc @mr-michael

**Comment by Erotemic** [comment]
@mhluongo Looking forward to it. I simply can't make a wallet right now, which is annoying. I have an existing wallet using the "Coin Wallet" Ubuntu app, but that doesn't have many integrations with other services I'm interested in using.

**Comment by mhluongo** [comment]
Pro-tip that I'm borderline horrified to share... if you right click on the extension popup and choose "inspect element", then minimize the dev tools... the extension will stay up even when it loses focus.

It's a terrible hack, but at least there is a hack.

**Comment by 0xDaedalus** [comment]
Will be addressed as part of upcoming onboarding revamp
