### ISSUE TITLE
Tx gets rejected by user while minting NFT on Doingud on Polygon

### ISSUE THREAD

**Issue by Eastban120** [tallyhowallet/extension#2116]
### Discord Discussion Link

Suggested by moderator

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

On Doingud NFT platform (https://doingud.com/creation/) on Polygon I tried to mint several NFTs.
Login with Tally Ho wallet is being done by injecting as MM.

### What did not work?

Whenever I click on Confirm the operation gets rejected by user:
<img width="863" alt="Captura de Pantalla 2022-09-02 a la(s) 18 53 31" src="https://user-images.githubusercontent.com/68087535/188281620-a5476acc-0d08-4f55-be91-593356ba6f5f.png">
<img width="769" alt="Captura de Pantalla 2022-09-02 a la(s) 18 54 04" src="https://user-images.githubusercontent.com/68087535/188281621-bd4e1e49-c3e2-49ea-b906-d9e8e424afe9.png">

### Version

v0.15.0

**Comment by Naxsun** [comment]
Tried to reproduce, same issue. Saw that when opening the transaction after, it gives a 'failed to broadcast' message.

<img width="280" alt="Screen Shot 2022-09-06 at 09 35 03" src="https://user-images.githubusercontent.com/71384922/188574792-9dc07db9-d516-4b22-b04a-66d7e15450f0.png">

**Comment by Naxsun** [comment]
Just tried with 0.14.1, there it still worked

**Comment by 0xDaedalus** [comment]
Stale
