### ISSUE TITLE
CEX deposit address recognized as contract address - warns for loss of funds

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2117]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send funds to a CEX

### What did not work?

Wallet warns this is a contract address and will result in a loss of funds

<img width="382" alt="Screen Shot 2022-09-04 at 14 37 06" src="https://user-images.githubusercontent.com/71384922/188327760-38606733-b1c6-4fee-841a-d6673267c093.png">

### Version

v0.15.0

**Comment by Naxsun** [comment]
Example: warning is received when sending funds to Coinlist (they use a contract), does not apply to Binance

**Comment by mhluongo** [comment]
Just needs a copy update IMO. Ideas on what it should say @Naxsun?

**Comment by Naxsun** [comment]
I assume we can not distinguish between a token contract and a different / CEX contract?

**If this is the case**
- Was: This is a contract address, sending assets will result in loss of funds
- Opt 1: This is a contract address, sending assets may result in loss of funds
- Opt 2: This is a contract address, confirm the address to prevent loss of funds
- Opt 3: The receiver is a contract address, be sure to verify the address

I'm inclined to option 3

**Comment by jagodarybacka** [comment]
I like 2, 3 is ok too

**Comment by 0xDaedalus** [comment]
I like 1 or 3

**Comment by Naxsun** [comment]
@mr-michael can we make a decision for a tweak for now? Currently also bridges show this message.

I propose to go for: This a contract address, be sure to confirm the address.

<img width="377" alt="Screen Shot 2022-09-18 at 14 44 58" src="https://user-images.githubusercontent.com/71384922/190902779-85b1b515-2507-4b30-8f88-bb556badfbc1.png">

**Comment by 0xDaedalus** [comment]
Resolved as part of https://github.com/tallyhowallet/extension/pull/2252
