### ISSUE TITLE
Standardize our process for using git tags.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#2156]
Per our live discussion, for whatever reason the `v0.15.1` tag doesn't show the expected Goerli behavior... but the prod extension and `main` do. Worth following up to fix our release process / make tags more useful.

_Originally posted by @mhluongo in https://github.com/tallycash/extension/issues/2148#issuecomment-1240910700_

We also have an issue where tags display as `Unverified` on github despite being created through a signed commit.  Possibly related.

**Comment by Shadowfiend** [comment]
Tags require separate signing, iirc. `git tag -s` does the trick, but that will also require a tag message I believe.
