### ISSUE TITLE
Can't swap on mainnet

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2200]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Attempted to swap from DAI to ETH on Mainnet. 

### What did not work?

I've asked more details on the nonces, last completed (Etherscan) and the pending approval transaction (Tally Ho activity list)

**User report:**
Submitted the approval transaction but over an hour later it still shows up as pending on the activity tab and the transaction (0xb79a73edf02963802a61ad8e0add516687c77f56f4e4eb1865f37e1a4ae06c32) doesn't show up on Etherscan. Tally's swap screen shows "Waiting for approval transaction..."

**Browser:** Google Chrome 105.0.5195.125 (Official Build) (x86_64)
**Operating System:** macOS 12.6 (21G115)

**Logs:**
[logs_v0_16_0__2022-09-14T20_47_44-05_00 (1).txt](https://github.com/tallycash/extension/files/9573204/logs_v0_16_0__2022-09-14T20_47_44-05_00.1.txt)

### Version

v0.16.0

**Comment by greg-nagy** [comment]
pending state change is properly picked up since #2527
