### ISSUE TITLE
Standardize how assets that come "built in" to the extension are looked up

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#222]
Treating network assets that come from token lists differently from fiat and base assets like ETH is cumbersome and error-prone.

**Comment by 0xDaedalus** [comment]
Closing b/c stale and even with the secondary comment not quite enough information about what exactly we're fixing.  As we increase test coverage for Indexing Service I expect the pain felt here will re-surface and we can make a more concrete issue.
