### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#223]
As we get closer to a public release, we need to start thinking about internationalization.

We won't have bandwidth for more than English for the first release, but preparing the extension with tagged strings will let the community pick up a lot of the slack.

**Comment by gasolin** [comment]
could replace with https://github.com/tallycash/extension/issues/438 since more concrete discussion there

**Comment by 0xDaedalus** [comment]
Closed in favor of https://github.com/tallyhowallet/extension/issues/438
