### ISSUE TITLE
Text scaling - overlapping text

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2235]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1020924642128564285

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View wallet balance

### What did not work?

![image](https://user-images.githubusercontent.com/71384922/190899773-fc381c7a-70ae-4dd4-a6f4-884c19831de6.png)

- Extension version (listed under menu):
  Version: 0.16.0_93902cc
- Browser (Chrome/Brave/...):
  Chrome
- Operating system (Windows/Mac/Other):
  Windows
- screen resolution
  1929 x 1080
### Version

v0.16.0

**Comment by 0xDaedalus** [comment]
No longer an issue
