### ISSUE TITLE
Optimism token balances not updated after wallet import

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2237]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Installed release 0.16.1 through the Github release page, imported a recovery phrase

### What did not work?

Only ETH is displayed, tokens are not for Optimism, they are for mainnet and Polygon. 'digging deeper' message is gone. Actitity tab is populated. In another install with this wallet, <0.16.1, the sLink balance is displayed.

Update: Made two in-wallet swaps, also these tokens are not displayed.

address: 0x77f6e4ea32f0b807dcaaddbec9dabe0131614cd5

<img width="369" alt="Screen Shot 2022-09-18 at 13 45 26" src="https://user-images.githubusercontent.com/71384922/190900462-c65a024d-2451-4610-9a42-5ad482be19a5.png">

<img width="378" alt="Screen Shot 2022-09-18 at 13 47 15" src="https://user-images.githubusercontent.com/71384922/190900493-17ed61f0-ce84-42b6-9940-91ad6eb70f52.png">

<img width="418" alt="Screen Shot 2022-09-18 at 13 47 55" src="https://user-images.githubusercontent.com/71384922/190900521-d8c59b19-08ce-4913-afc6-60b0a784200c.png">

[logs_v0_16_1__2022-09-18T13_45_29+02_00.txt](https://github.com/tallycash/extension/files/9593882/logs_v0_16_1__2022-09-18T13_45_29%2B02_00.txt)

### Version

v0.16.1

**Comment by Naxsun** [comment]
The SLINK did update eventually, I estimate after ~ 30 minutes

**Comment by jagodarybacka** [comment]
I see this issue from time to time but I cannot find a way to reproduce it reliably. I won't close this one as I believe it is not solved but I don't know what we can do about it right now.

**Comment by 0xDaedalus** [comment]
Stale
