### ISSUE TITLE
Bug? capturing logger stack traces

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#224]
I'm losing the stack track for `logger.error(...)` calls, though it's then logging what looks like a slightly munged original stack trace as well. Open to being told I'm using this wrong!

![Screenshot from 2021-09-11 18-28-42](https://user-images.githubusercontent.com/427505/132963118-8ee6f9e2-43f8-4313-b93c-846ec23e6a2f.png)

**Comment by itsrachelfish** [comment]
@mhluongo @greg-nagy I believe this issue can be closed now? :thinking:

**Comment by SJQuality** [comment]
@mhluongo bump... is this still an issue?

**Comment by 0xDaedalus** [comment]
This no longer seems to be an issue ✅
