### ISSUE TITLE
Can't send MATIC on Polygon

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2320]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1023942118135320668

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send MATIC

### What did not work?

The transactions were set-up, completed, but funds weren't transferred. The user tried to transfer DAI, which worked. The user then swapped the MATIC to USDC and was able to successfully send the USDC.

<img width="1069" alt="Screen Shot 2022-09-28 at 08 09 53" src="https://user-images.githubusercontent.com/71384922/192701114-8ef1910f-ff81-478b-b9e1-e9f26396d4a7.png">

![image](https://user-images.githubusercontent.com/71384922/192701197-67e8d396-cd82-4322-93eb-cd621ac03cf9.png)

- https://polygonscan.com/tx/0xb8cdfd53f488a3e2c283c2a5791527e5c79bd14b61857c0d04054cd1313e9a43
- https://polygonscan.com/tx/0x935157be6268cf56dd14df165b2e97f66b0eecaf3c43da8169d4b5b0d0e8bba7
- https://polygonscan.com/tx/0x2a277fba387deab72a17bf888b0e9df8f83c0f81b9c263ee5f5545e0a67b9d0a
- https://polygonscan.com/tx/0x6210d081128f5b995c364c121dd045d49d2066dfc114696e8cbedfad3586c9f6

### Version

v0.16.3

**Comment by 0xDaedalus** [comment]
No longer seems to be an issue
