### ISSUE TITLE
Galxe Optimism NFT not showing image and title

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2323]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View Galxe Optimism NFTs in the extension

### What did not work?

For below NFT, it took >30 minutes to load the image and title. The extension had high CPU usage, so I removed it after 30 minutes and installed it again. Afterwards this NFT was loaded instantly.

https://optimistic.etherscan.io/token/0x56FE60179c13B6492c6501D36e77CCD9FB86d7c2?a=8233 

Another NFT, still isn't showing
https://optimistic.etherscan.io/token/0x671CFd5882b5F48654EC99ec8F997Ed6C6031DF9?a=1090

Extension:
<img width="363" alt="Screen Shot 2022-09-28 at 11 44 58" src="https://user-images.githubusercontent.com/71384922/192747199-3df71669-5e27-4a72-9a08-863c90062424.png">

Quix:
<img width="759" alt="Screen Shot 2022-09-28 at 11 45 48" src="https://user-images.githubusercontent.com/71384922/192747394-cfd618ea-6ea3-466c-af57-94cf9bac2ccd.png">

### Version

v0.16.3

**Comment by 0xDaedalus** [comment]
Stale
