### ISSUE TITLE
Optimism & Mainnet - transactions- fail to broadcast

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2329]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1024998433804783746

### What browsers are you seeing the problem on?

Chrome, Brave

### What were you trying to do?

In-wallet swap

### What did not work?

- What is the issue you're observing: I try to approved asset on OP and end up with transaction failed to broadcast every time. I also tried it on Mainnet and it's not a problem.
- What triggered the issue (Send, receive, connect to dapp etc): Approve

User has 0.07 ETH on Optimism

- Extension version (listed under menu): Version: 0.16.3_5fee76d
- Browser (Chrome/Brave/...): Brave
- Operating system (Windows/Mac/Other): Windows

[logs_v0_16_3__2022-09-29T17_51_1707_00.txt](https://github.com/tallycash/extension/files/9674067/logs_v0_16_3__2022-09-29T17_51_1707_00.txt)

### Version

v0.16.3

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
