### ISSUE TITLE
Extension crashes on brave

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2352]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/1011550980707463238/1025458747239305277

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Open the extension

### What did not work?

![image](https://user-images.githubusercontent.com/71384922/193411143-0e38a76e-1029-43d4-83e0-6827f2dd9641.png)

### Version

v0.16.3

**Comment by Naxsun** [comment]
Similar report https://discord.com/channels/808358975287722045/888500174685614090/1022780859134255164

**Comment by Naxsun** [comment]
Similar report as well https://discord.com/channels/808358975287722045/888500174685614090/1014106524957802536

**Comment by 0xDaedalus** [comment]
Stale
