### ISSUE TITLE
Balance update - Token lists blocked

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2356]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1026029286752260156

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View balances, swap

### What did not work?

The wallet wasn't displaying ERC20 token balances, just ETH. The user was connected through a VPN.

The logs showed: "Error fetching, validating, and saving token list"

Asked the user to open a token list link in his browser, which didn't work etiher. 
https://ipfs.io/ipfs/////bafybeifeqadgtritd3p2qzf5ntzsgnph77hwt4tme2umiuxv2ez2jspife

Afterwards the user tried to open the link on his phone --> worked. The user tried the extension on a different system, there the balances were updated correctly.

Some ideas:
- Are there actions the user could take / look into to get it working on his original system
- Can we make this less likely to happen (may need more info from the user first?)
- Can we improve how we indicate to a user why his balances aren't loaded?

Full logs:
[logs_v0_16_3__2022-10-01T14_05_2505_00 (2).txt](https://github.com/tallycash/extension/files/9696305/logs_v0_16_3__2022-10-01T14_05_2505_00.2.txt)

### Version

v0.16.3

**Comment by 0xDaedalus** [comment]
Stale
