### ISSUE TITLE
Can't LP on Velodrome

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2358]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Deposit USDC and DAI on Velodrome

### What did not work?

When depositing into an LP on https://app.velodrome.finance/liquidity/create a user can either decide to 

1) deposit & stake in a combined flow. Deposit assets, stake LP tokens
2) deposit assets in a separate action, and optionally stake the LP tokens

Both of these consists of multiple transactions, and these aren't handled well.

Pool tested: USDC & DAI (Add liquidity to vAMM-USDC/DAI)

**With flow 2, what should happen:**
- an approve transaction for DAI spend
- an approve transaction for USDC spend
- a deposit transaction

**What happens:**
- two approve transactions for 1 asset (either USDC or DAI)  or at least two UI window popovers. If signed, the transaction is dropped and and the UI prompts "the user rejected the request"
- the transaction is not visible on optimistic.etherscan

Dropped tx hash: https://optimistic.etherscan.io/tx/0x7480b9fd2626be7b261c00cb84e36d1c891be4fa7dce6f2811c543b311c0f67a

<img width="1456" alt="Screen Shot 2022-10-03 at 14 20 04" src="https://user-images.githubusercontent.com/71384922/193576034-39dcc603-3568-439c-875d-b38db7ba64d3.png">

<img width="1164" alt="Screen Shot 2022-10-03 at 12 31 07" src="https://user-images.githubusercontent.com/71384922/193576092-b4cf70ba-d408-4acf-9469-7fcba6a5f0f8.png">

Logs:
[logs_v0_16_5__2022-10-03T14_25_55+02_00.txt](https://github.com/tallycash/extension/files/9697434/logs_v0_16_5__2022-10-03T14_25_55%2B02_00.txt)

### Version

v0.16.4

**Comment by tallysam** [comment]
I saw Nax do this in a call recently.
