### ISSUE TITLE
ETH balance on Optimism not updated, ERC20 balance is updated

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2376]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1026919790016733185

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

View balances

### What did not work?

The ERC20 balance, USDC, is shown correctly. The ETH balance however isn't correct. Also the wallet $ balance isn't displayed.

![image](https://user-images.githubusercontent.com/71384922/193932974-429065e1-8b62-4ad6-81c5-48166745767f.png)

![image](https://user-images.githubusercontent.com/71384922/193933056-141a5f78-73a5-4fe2-b74e-e0d2c0782a9a.png)

The user provided logs:
[logs_v0_16_5__2022-10-05T03_52_3607_00.txt](https://github.com/tallycash/extension/files/9711002/logs_v0_16_5__2022-10-05T03_52_3607_00.txt)

Update: The user is also reporting dropped transactions

![image](https://user-images.githubusercontent.com/71384922/193933315-b4b6372f-4083-4bae-a392-5374515dec91.png)

![image](https://user-images.githubusercontent.com/71384922/193933333-5571fc02-2f5a-48ef-95b1-8611c01355f1.png)

### Version

v0.16.5

**Comment by 0xDaedalus** [comment]
No longer an issue
