### ISSUE TITLE
Transactions not signing on Velodrome dapp

### ISSUE THREAD

**Issue by chlolands** [tallyhowallet/extension#2407]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was trying to swap from USDC to Velo on [Velodrome ](https://app.velodrome.finance/) to complete this [Optimism GALXE quest. ](https://app.optimism.io/quests/velodrome-provide-liquidity)

### What did not work?

Every single time, I kept getting the error message "user rejected the request." I had plenty of ETH in Optimism to account for gas fees, as well. 

### Version

v0.17.0

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
