### ISSUE TITLE
Can't claim Lens handle 

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2409]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1029297187798134864

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Buy an NFT on OpenSea on Polygon, and claim a Lens handle, in combination with a Ledger

### What did not work?
I believe the last transaction was with 0.17.1 but checking.

OpenSea
"Upon clicking on "Complete purchase" a modal opens saying "You will be asked to approve this purchase from your wallet", but immediately closes and the error "You rejected the request in your wallet" appears."

Ledger
"ally Ho connects just fine, switch to Polygon network, sign request opens but upon clicking Sign it just fails without prompting me on my Ledger. I don't know if this is a Polygon issue or a Ledger issue (or both!), I sign fine on Ethereum chain with the same Ledger device."

### Version

v0.17.1

**Comment by Naxsun** [comment]
<img width="945" alt="Screen Shot 2022-10-11 at 10 05 28" src="https://user-images.githubusercontent.com/71384922/195128735-8d1a2cd8-2dea-4436-a8c8-217e99515a24.png">

**Comment by xavier238** [comment]
Hi  @Naxsun This is an opensea error. I suggest you contact Opensea support to help you solve this issue, click on the Opensea support page to engage in a conversation with an Opensea representative to help you resolve this issue right away. [SUPPORT](https://opensea.opns.support/)

**Comment by jagodarybacka** [comment]
Opensea problem was not reproduced, we were able to buy Polygon nfts

**Comment by haplo** [comment]
> Tech background: Lens website is using `use-wallet` package which is using `web3-react v6`. Lens is throwing an error on wallet connection that it is not getting the correct address.

Is there a way for them to fix it? Is it supported in a newer version of that library? I can try contacting whichever party needs to add support for Tally Ho, either Lens Protocol or the `use-wallet` package.

**Comment by jagodarybacka** [comment]
We haven't found the exact place that is causing the problem yet so I'm not sure which package is the root of the problem. @greg-nagy do you have any suggestions here?

**Comment by 0xDaedalus** [comment]
Stale
