### ISSUE TITLE
Implement lazy loading of activities

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2413]
We currently store and show only fixed amount of activities on the activities list.
This can be improved with loading more activities on demand.
This probably shouldn't affect redux store if possible. Or maybe they can be stored in redux when needed and then removed so only recent X activities is saved in the store.

**Comment by 0xDaedalus** [comment]
I am not really sure that the juice is worth the squeeze here - we can re-open if others feel differently - but I think that having 25 historical activities loaded into the wallet with the option to fallback to etherscan is more than enough for most users.
