### ISSUE TITLE
Analytics: Sorry to see you go

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#2421]
Made a quick design for this, nothing fancy but should help unblock posthog implementations

**Design**
![image](https://user-images.githubusercontent.com/80846886/195594139-b0de9156-7670-468c-8ddd-d8a78c5cf0f5.png)

**Figma Link**
[Figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=13915%3A266991)

It's using existing assets, from Ledger onboarding page and icons from tally.cash

**Comment by 0xDaedalus** [comment]
Complete ✅
