### ISSUE TITLE
Rabbithole isn't detecting our network state

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2430]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1030196568571248771

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Claim an nft on rabbithole.gg

### What did not work?

It doesn't detect the network state. In below state it requires the extension to switch to Optimism, which it's already on. Refresh, select network again etc doesn't work.

<img width="1424" alt="Screen Shot 2022-10-14 at 08 04 54" src="https://user-images.githubusercontent.com/71384922/195854074-f54c169c-5515-4145-be8c-4103f32b8dac.png">

### Version

v0.17.1

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
