### ISSUE TITLE
Change number formatting in activities list item

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2438]
This number is formatted differently than for example account balance in Wallet and Portfolio - we should unify it

<img width="407" alt="Снимок экрана 2022-10-14 в 15 10 36" src="https://user-images.githubusercontent.com/67752860/195843906-9a4f2cce-e15c-4b77-b7af-29e408790b91.png">

_Originally posted by @alterkahn in https://github.com/tallycash/extension/issues/1786#issuecomment-1278923758_

**Comment by kgelpes** [comment]
Can I work on this issue?

**Comment by jagodarybacka** [comment]
@kgelpes sure!

**Comment by kgelpes** [comment]
Can't reproduce the issue, seems to have been fixed on https://github.com/tallyhowallet/extension/pull/2311
![image](https://user-images.githubusercontent.com/31427153/213618260-dd42e775-d3b7-4773-bb05-a195ff6c442e.png)

**Comment by jagodarybacka** [comment]
@kgelpes cool thank you for checking this issue, let's close it then!
