### ISSUE TITLE
Can't "Reject" SIWE from read only account

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2440]
Try to sign a message on https://login.xyz/#tryitout with read only account.
It should allow to reject but Reject button is disabled.

![image](https://user-images.githubusercontent.com/20949277/196163474-fb4629c8-c250-4ccf-a229-f86d798a82cf.png)

**Comment by kkosiorowska** [comment]
The issue is no longer there.

![Screenshot 2022-12-30 at 15 07 34](https://user-images.githubusercontent.com/23117945/210078869-da0191ed-13c0-4a64-bc30-4f8b19a45de1.png)
