### ISSUE TITLE
UI bug that asks me to approve tokens twice

### ISSUE THREAD

**Issue by alterkahn** [tallyhowallet/extension#2441]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1031546181786013757

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

After i approve a certain token number to spend, the wallet wants me to "approve" it again, and only after I re-fill the amount it changes the button to "get final quota". And this repeats constntly.

### What did not work?

everything else worked well, except this https://github.com/tallycash/extension/issues/1786#issuecomment-1278923758

### Version

v0.17.1

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
