### ISSUE TITLE
View Asset tooltip visual bug

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#2465]
Test wallet - optimism network

<img width="250" alt="image" src="https://user-images.githubusercontent.com/94649004/197032798-f0574625-6d82-4153-8ec1-b53a9f3cc80f.png">

**Comment by Shadowfiend** [comment]
This is fixed in #2461 if we're willing to wait; otherwise we can cherry pick https://github.com/tallycash/extension/commit/0f3f74cbd9a11c0d8a0abeb703b02ad97ed67843 .

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
