### ISSUE TITLE
Optimism NFT not showing in wallet

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2483]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1033133884998701187

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user wanted to view all 6 NFTs

### What did not work?

Only 5 of the 6 NFT's are showing. There is also not a 'no image' preview, it's not showing as an asset at all.

- Address: 0x2267A379ACb4973Bfc025Ee0ebe591a1A2AB966e
- All assets: https://optimistic.etherscan.io/address/0x2267a379acb4973bfc025ee0ebe591a1a2ab966e#tokentxnsErc721
- Missing NFT: https://galxe.com/nft/1114/0x671CFd5882b5F48654EC99ec8F997Ed6C6031DF9

Reproduced by adding the account as a read only address 

In wallet:
![image](https://user-images.githubusercontent.com/71384922/197480400-3751672b-c17a-416c-a44b-d38b1d80f720.png)

On Quix:
<img width="1139" alt="Screen Shot 2022-10-24 at 10 20 40" src="https://user-images.githubusercontent.com/71384922/197480862-cb7fce8b-3157-426b-8ca4-93772ac7762d.png">

### Version

v0.17.3

**Comment by jagodarybacka** [comment]
SImpleHash just doesn't include this NFT in the response. 
I've tried refreshing metadata via Quix - no effect, via SimpleHash refresh endpoint - 404, it doesn't know about this NFT. We can probably contact them because I don't see any other solution in their docs.
