### ISSUE TITLE
Failed to broadcast transactions

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2484]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1033447876073902161

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up transactions

### What did not work?

Several users reported 'failed to broadcast' errors. 

**User Lucha:**
https://discord.com/channels/808358975287722045/888500174685614090/1033448097948389417
Did not receive more info yet

**User Bentley:**
https://discord.com/channels/808358975287722045/888500174685614090/1033500094982533150

![image](https://user-images.githubusercontent.com/71384922/197482319-54175942-0352-4a9a-851b-3e5c874a9c90.png)

Browser: Kiwi
Logs: 
[logs_v0_17_3__2022-10-23T09_37_4401_00 (1).txt](https://github.com/tallycash/extension/files/9850068/logs_v0_17_3__2022-10-23T09_37_4401_00.1.txt)

**User Deen:**
https://discord.com/channels/808358975287722045/888500174685614090/1033510069679161344
Did not receive more info yet

### Version

v0.17.3

**Comment by Naxsun** [comment]
**User: Triller**
https://discord.com/channels/808358975287722045/888500174685614090/1032608217865404457
Optimism
Address: 0x22523f7b8c73d1e58b933ad456571fa3031a7ba6

**Comment by 0xDaedalus** [comment]
Stale
