### ISSUE TITLE
Validate BIP-39 seed phrases in onboarding

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#249]
[BIP-39](https://www.blockplate.com/pages/bip-39-wordlist) specifies multiple word lists for recovery phrases.

We should...
* validate the number of words (12 for legacy import, 24 for new wallets) in a recovery phrase
* validate that all words in the phrase are in the English word list
* validate the last (checksum) word in the phrase

As far as I know, MM and other popular Ethereum wallets just work with the English word list. We can explore using the others, but it's secondary before launch.

**Comment by 0xDaedalus** [comment]
Closed because this has been completed as part of the new onboarding flow.
