### ISSUE TITLE
Unable to connect to Hop Protocol

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#2518]
https://user-images.githubusercontent.com/7005061/198405203-42e668a4-f0e3-4a51-baaf-fe367a72a1a8.mov

**Comment by 0xDaedalus** [comment]
Unfortunately the design of the connection screen is to blame here:

https://user-images.githubusercontent.com/94649004/198421497-ff4971a7-f1db-4392-b520-8446bfa00898.mov

Not sure how much we can do on this front.

**Comment by Naxsun** [comment]
I've already reached out to Hop on this

**Comment by 0xDaedalus** [comment]
No longer an issue - Tally is now a connection option on hop protocol
