### ISSUE TITLE
Asset duplication

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#2559]
It appears we're reported duplicated MATIC ERC-20 balances on Ethereum, likely due to poorly merged asset metadata.

![Screenshot from 2022-11-04 16-00-08](https://user-images.githubusercontent.com/427505/200071319-2742ecfb-f178-4b68-b60b-5feb5097bc52.png)

Unlike some other issues [we have with MATIC](https://github.com/tallycash/extension/issues/2403), I don't think this has to do with it being an ERC-20 on one network (chain ID 1) and a base asset on another (chain ID 137).

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
