### ISSUE TITLE
Increase a hit box area for icon-only buttons

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2567]
It is hard to click buttons that are just an icon - user has to click directly on the icon. It would be nice to add clickable padding so the area that is clickable is a "square" around the icon.

![image](https://user-images.githubusercontent.com/20949277/200361848-45678354-f0f9-4c6d-b941-06362c05a704.png)

**Comment by 0xDaedalus** [comment]
Resolved ✅

**Comment by jagodarybacka** [comment]
It got resolved for these icons from the screenshot but for example on slideups `X` button is still only clickable directly on the icon 
![image](https://user-images.githubusercontent.com/20949277/219331374-29964ee4-b53e-4387-aaa3-fda5e96d7bfc.png)
