### ISSUE TITLE
Can't connect to Across (Web3-onboard)

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2592]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Connect to [Across](https://across.to/)

### What did not work?

Some users can't connect Tally Ho to https://across.to/ 

For the majority of users it works flawlessly. Across uses Web3-onboard, and this usually handles multiple browser wallets well. So far we haven't been able to reproduce.

The error message that a user receives is: 'Cannot assign to read only property 'request' of object '#'

![image](https://user-images.githubusercontent.com/71384922/201325941-d7313796-ad7d-4b73-9624-1744ccd13b5d.png)

So far I've tried to reproduce, but failed through:
- Chrome and Brave
- Connecting hot wallets, Ledger and Read only accounts
- Having multiple browser wallets enabled
- Having only Tally Ho as browser wallet enabled
- Tally Ho default on/off

### Version

v0.17.9

**Comment by Naxsun** [comment]
A user shared that has this error shared below console info 

![image](https://user-images.githubusercontent.com/71384922/201335291-1011eb2d-7be1-483f-be07-4d7de5331a82.png)

**Comment by Naxsun** [comment]
There's one extension identified that's interfering with Tally Ho and triggers this error.

https://www.pocketuniverse.app/

Once installed a user can't connect with Tally Ho to any dapp that uses web3onboard onboard. MetaMask and Coinbase still work.

Will add here if we find more dapps.

**Comment by pxrl** [comment]
I can echo the input from @Naxsun here - the Across Discord has had many instances of users with this issue. The Tally integration is important for Across and we're happy to provide feedback on any patches.

**Comment by pxrl** [comment]
@0xDaedalus Is there a public thread with Blocknative that we can participate in? We're happy to add some emphasis on our end.

**Comment by greg-nagy** [comment]
@0xDaedalus should we remove this from our sprint board / close the issue altogether because we have nothing to do here?

**Comment by 0xDaedalus** [comment]
> @0xDaedalus should we remove this from our sprint board / close the issue altogether because we have nothing to do here?

Yes
