### ISSUE TITLE
Extension opens multiple times on Connext bridge

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2665]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1044861392794161212

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to connext bridge

### What did not work?

User: "it open repeatly when i open connext bridge site and switch network"

![image](https://user-images.githubusercontent.com/71384922/203492042-cc515d24-6f97-4361-8a9e-6164b3d3d319.png)

### Version

v0.18.2

**Comment by greg-nagy** [comment]
This issue focuses on connext bridge

We allow multiple windows by design and changing that would require some more work than ideal for a single ticket.

**Comment by 0xDaedalus** [comment]
No longer seems to be an issue ✅
