### ISSUE TITLE
Unexpected error when sending ETH on Arbitrum

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2713]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1048277384824094740

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send ETH on Arbitrum

### What did not work?

Received bellow error:
![image](https://user-images.githubusercontent.com/71384922/205595773-8b50c0af-c5d1-45bb-88c7-3dbd59f4169a.png)

Logs:
[logs_v0_18_3__2022-12-02T18_05_48-05_00.txt](https://github.com/tallycash/extension/files/10152442/logs_v0_18_3__2022-12-02T18_05_48-05_00.txt)

After 2 re-installs the user was able to send funds.

### Version

v0.18.3

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
