### ISSUE TITLE
Network network menu isn't scrollable, causing Goerli to partially drop off

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2742]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Scroll networks

### What did not work?

We need scrolling in the network selection menu, which is awesome!

<img width="380" alt="Screen Shot 2022-12-09 at 20 11 17" src="https://user-images.githubusercontent.com/71384922/206779565-d60b5fcc-6196-48f8-a316-33b61b6d21dc.png">

### Version

v0.18.5

**Comment by mhluongo** [comment]
Closed by #2821
