### ISSUE TITLE
Spike - Daylight

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#2743]
Questions:

- Look to the Pitch for an outline of possible red flags to check for
- Can we get data that we need for the screens that Vlad has designed using the API? https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=15103%3A309472
- Are there rate limit worries?
 

Design - https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=15103%3A309472

Pitch - https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Daylight_suuN-#_luFqK

**Comment by kkosiorowska** [comment]
Daylight was released in [v0.23.0](https://github.com/tallyhowallet/extension/pull/3009) So I closed this task.
