### ISSUE TITLE
Arbitrum Swaps Not Working

### ISSUE THREAD

**Issue by chlolands** [tallyhowallet/extension#2747]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was trying to swap between ETH to Magic + ETH to USDC on Arbitrum.

### What did not work?

Every Arbitrum swap is giving me a "transaction failed to broadcast" message. Swaps work fine on mainnet, Optimism + Polygon.

### Version

None

**Comment by 0xDaedalus** [comment]
This is no longer an issue ✅
