### ISSUE TITLE
Show asset prices (if available) when adding a custom network.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#2761]
Depends on https://github.com/tallycash/extension/issues/2759

I think the way forward here is to pull down asset_platforms with valid chain_identifiers from https://api.coingecko.com/api/v3/asset_platforms and then maintain our own json file of the results.  Then, when a network is imported, if the chainId being imported matches one we have on file - set the network metadata's `coingeckoPlatformID` to the corresponding `id` from coingecko.

We can also do this by pinging the endpoint on-demand but we want to do everything we can to avoid getting rate limited on coingecko - so we should persist the mapping in code if we can.

**Comment by puppycodes** [comment]
- Shows asset prices on custom networks when available
Done!
