### ISSUE TITLE
BNB chain.- NFT image and name not showing inside the wallet

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2774]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View a BNB chain NFT inside the extensionm

### What did not work?

Image and name aren't loading

<img width="218" alt="Screen Shot 2022-12-14 at 14 48 26" src="https://user-images.githubusercontent.com/71384922/207611931-777074c9-cceb-4ffa-93b9-78ee8a5d38be.png">

Address:0x77f6e4ea32f0b807dcaaddbec9dabe0131614cd5
https://bscscan.com/address/0x77f6e4ea32f0b807dcaaddbec9dabe0131614cd5#tokentxnsErc1155

Same NFT on OpenSea: https://opensea.io/assets/bsc/0xe5b184875dd4f09f687d497d76c22d20aec67788/7074

I do want to flag that I also don't see the asset on tofunft.

This is the same NFT as in issue https://github.com/tallycash/extension/issues/2765 but don't know if that's related.

### Version

v0.18.5

**Comment by kkosiorowska** [comment]
I looked into the issue.  This isn't related to BNB chain a with specific NFTS. I mean that `name` and `image_url` come empty from the API. We would have to expand change the property from which we take information about it. Take a look that for other nfts these fields are not empty. 

<img width="240" alt="Screenshot 2022-12-14 at 17 00 29" src="https://user-images.githubusercontent.com/23117945/207653519-d5abb703-3b08-4d73-ac3a-7c6769ea39e7.png">

<img width="640" alt="Screenshot 2022-12-14 at 16 58 38" src="https://user-images.githubusercontent.com/23117945/207654239-6e17982d-b3f9-4042-b1d4-a961ddd5a006.png">

**Comment by kkosiorowska** [comment]
I took another look at this task. Unfortunately, the data from the api comes empty. I haven't found a way to extract them from something else.

**Comment by Naxsun** [comment]
It would be good to inform the api provider of this, so they can look into it. Is this SimpleHash?

**Comment by jagodarybacka** [comment]
I think it is not necessary to inform them, SH is indexing NFTs in an async manner so it's not guaranteed that the data will be there when we want to. For example, this NFT has been updated:
![image](https://user-images.githubusercontent.com/20949277/211294812-d98bbfcd-61a0-4c8c-bb1a-c2a67925816f.png)
![image](https://user-images.githubusercontent.com/20949277/211295164-6bac38ee-bea8-45f7-be15-cedfe0c132e3.png)
