### ISSUE TITLE
Add tests for NFTs service

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2776]
Tests for NFTs service:

- test service start - NFTs should be fetched once chain service started
- test if NFTs are fetched when a new account is added to tracked accounts in the chain service

Tests for NFTs database

- check if NFTs and collections are added to the database correctly
- check if collections are updated with `updateCollectionData`
- check if you can remove NFTs for the given address with `removeNFTsForAddress`
- check if you can remove NFTs by id with `removeNFTsByIDs`

**Comment by tallysam** [comment]
After discussion we would like to break this into multiple tickets of test writing.

**Comment by jagodarybacka** [comment]
New tasks: https://github.com/tallyhowallet/extension/issues/3043 https://github.com/tallyhowallet/extension/issues/3045 https://github.com/tallyhowallet/extension/issues/3044
