### ISSUE TITLE
In-wallet swap tx marked as dropped - but actually succesfully completed

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2803]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

In-wallet swap

### What did not work?

Extension lists tx as dropped.

https://optimistic.etherscan.io/tx/0x10a082a1597a8cdddc2695e9cad2a558c1f18dfdc3950e437cc94d7e69d6cc80
https://user-images.githubusercontent.com/71384922/208433610-6092cff4-541c-43c0-9aee-512ee9920e15.mov

[logs_v0_18_6__2022-12-19T14_12_02+01_00.txt](https://github.com/tallyhowallet/extension/files/10259489/logs_v0_18_6__2022-12-19T14_12_02%2B01_00.txt)

### Version

v0.18.6

**Comment by 0xDaedalus** [comment]
Closed in favor of https://github.com/tallyhowallet/extension/issues/2803
