### ISSUE TITLE
Dropped transactions on mainnet

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2808]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1052904602518949949

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send ETH

### What did not work?

- Getting consistently dropped transactions
- The wallet doesn't indicate 'failed to broadcast', but 'transaction signed, broadcasting'
- There is an issue with the nonces, because the video recording below shows a nonce 3, where the actual nonce for the account at that time should have been 0
- A complete re-install didn't fix the issue.

Address: 0x34f0792b68e93c2bc01b59c8976535b161118d4b

https://user-images.githubusercontent.com/71384922/208902489-4e9f053d-5592-427b-a0a7-95d9023ecfbe.mov

<img width="294" alt="Screen Shot 2022-12-21 at 13 08 14" src="https://user-images.githubusercontent.com/71384922/208901848-d6e1e6c4-fcc5-4522-a2d2-7399c9f0ac82.png">

Logs: [logs_v0_18_5__2022-12-15T12_50_4201_00 (2).txt](https://github.com/tallyhowallet/extension/files/10277484/logs_v0_18_5__2022-12-15T12_50_4201_00.2.txt)

### Version

v0.18.6

**Comment by greg-nagy** [comment]
After #2160 is in place we should fix the nonce release logic to set the proper nonce after a release [here](https://github.com/tallyhowallet/extension/blob/634bcbdbdd29c875fcfcc0fe18b926e02d230773/background/services/chain/index.ts#L789-L798)
