### ISSUE TITLE
Why can't uniswap exchange tokens for accounts imported with "Read-only address"？

### ISSUE THREAD

**Issue by Joanna0123456789** [tallyhowallet/extension#2839]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

<img width="389" alt="image" src="https://user-images.githubusercontent.com/95467092/210494708-a09cf4ee-e128-4628-a640-5738092275f3.png">

### What did not work?

Why can't uniswap exchange tokens for accounts imported with "Read-only address"？

### Version

v0.18.6

**Comment by am1993421** [comment]
You need to import the seed phrase to prove that you have the right to use this address.
Otherwise it can only read, which means read-only

**Comment by jagodarybacka** [comment]
Thank you @am1993421 - that's right, read-only accounts can't sign transactions.

**Comment by Joanna0123456789** [comment]
Hello, I would like to ask why you can not import the account through "private key or keystore"?



At 2023-01-04 18:12:57, "Joe" ***@***.***> wrote:

You need to import the seed phrase to prove that you have the right to use this address.
Otherwise it can only read, which means read-only

**Comment by jagodarybacka** [comment]
@Joanna0123456789 We don't support this feature right now, you can vote on it on the [feature requests list](https://tally-ho.upvoty.com/b/feature-requests/can-import-private-key/)
