### ISSUE TITLE
Match asset order on NFT tab and Portfolio tab

### ISSUE THREAD

**Issue by alsoknownaslj** [tallyhowallet/extension#2866]
Match the asset order on NFT and Portfolio tabs. Currently NFT tab says "N Collections | N NFTs | N Badges" and Portfolio says "N NFTs in N Collections with N Badges."

Close-up and full screenshots below.
<img width="383" alt="Screenshot 2023-01-13 at 4 24 14 PM" src="https://user-images.githubusercontent.com/104520552/212421936-5df45425-7674-479e-98c0-92525c9b1863.png">
<img width="368" alt="Screenshot 2023-01-13 at 4 12 21 PM" src="https://user-images.githubusercontent.com/104520552/212422101-3a2604a2-1f6e-4cb2-8e7f-dedf345a14f5.png">

<img width="383" alt="Screenshot 2023-01-13 at 4 23 29 PM" src="https://user-images.githubusercontent.com/104520552/212421814-d4f6ec37-45b9-480b-af3c-f86962a82e2b.png">
<img width="383" alt="Screenshot 2023-01-13 at 4 13 14 PM" src="https://user-images.githubusercontent.com/104520552/212421852-aecb2bc7-39f8-49cb-91f5-587286e1d6b2.png">

**Comment by VladUXUI** [comment]
Agreed! but it's not immediately clear that filtering NFTs in NFT page will result in Portfolio page changes. So we should add some sort of indicator for it. 
Maybe a text is enough?

Filters-------
<img width="583" alt="image" src="https://user-images.githubusercontent.com/80846886/212660534-83e6c046-5b49-48e0-8a61-641057a53f2f.png">


Portfolio-------
<img width="583" alt="image" src="https://user-images.githubusercontent.com/80846886/212661223-4cfb6f3f-8463-4c24-9be4-fdcbce47dbb2.png">
