### ISSUE TITLE
GALXE NFTs not grouped by collection

### ISSUE THREAD

**Issue by alsoknownaslj** [tallyhowallet/extension#2868]
Not sure if this is a bug: under the NFTs tab, badges are not grouped by collection like they are in the Wallet tab.

The top two GALXE NFTs are from the same smart contract:  `0x9e22a752C4eD3D6C5DaB0123ED6A1C7eCF575200`

<img width="383" alt="Screenshot 2023-01-13 at 4 54 46 PM" src="https://user-images.githubusercontent.com/104520552/212430626-78388c22-f2de-47f7-babb-ad2dec4eff0e.png">

**Comment by jagodarybacka** [comment]
Hey this was a design request that badges are not grouped into collections. On the Wallet page they are grouped as they are displayed together with other NFTs.
