### ISSUE TITLE
Visually Disable NFT and Swaps on unsupported networks

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#2959]
NFT & Swap buttons should be disabled with a tooltip when connected to a network that does not support NFTs / Swaps

**Comment by jagodarybacka** [comment]
The NFTs tab shouldn't be disabled regardless of the network as this is like a "NFT Portfolio". Also NFTs tab will replace swaps button so I think there is no need to disable it here if we will get rid of it very soon.
We should disable Swaps button on the Wallet page.

**Comment by VladUXUI** [comment]
Hey @0xDaedalus, per our previous discussion, let's remove any functionality that a particular chain doesn't support atm.
It created confusion around "is this temporary" "is it something wrong with it" and so on
