### ISSUE TITLE
Daylight ability filtering not working properly

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2964]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Filter out Daylight abilities

### What did not work?

Version 0.20.0dc1fc0b

- Initially Daylight showed I had 3 open abilities
- When changing the filter from open to all, this changed to a large list -> that's ok
- However, afterwards applying other filters (open, closed, deleted) doesn't clean the list anymore. It remains to show 'all abilities'

**Update:**
- as soon as you minimize the extension, and re-open it, the filtering is applied correctly
- as soon as you switch a tab, and go back to abilities, the filter is also applied correctly

https://user-images.githubusercontent.com/71384922/216003638-f5a5c32a-b611-4d4b-ad00-3a9947ed0cfe.mov

Side note: After changing the filter it also shows the total amount of abilities as 'new' (in this recording 11). For me 'new' is slightly confusing, like I would expect this to be things that I didn't see before. Maybe just the number would be reduce some confusion. Or make this number just show Open abilities, and name it 'x open'.

### Version

v0.20.0

**Comment by VladUXUI** [comment]
Very good sidenote @Naxsun 
Talked to Karolina about it a bit, and we are going to change New to Open. And the number in the banner would be
Open, but filtering out addresses and turned off abilities

**Comment by Naxsun** [comment]
Sounds good! Would 'turned off then be below categories?
- Deleted 
- Expired
- Closed --> is this 'Completed'

So when I act on an ability, and I complete the task, it'll become closed? If that's the case maybe Completed would be an option as well, to differentiate it more from Expired

**Comment by kkosiorowska** [comment]
> So when I act on an ability, and I complete the task, it'll become closed? If that's the case maybe Completed would be an option as well, to differentiate it more from Expired

I agree with you. Let's change it to `Completed`. @VladUXUI what do you think?

**Comment by VladUXUI** [comment]
These are the terms we were suggested to use by the Daylight team, this is what they use.
I don't know if some Abilities can be closed but not completed or expired? i can't think of any...

Good to change on my end, just providing context
