### ISSUE TITLE
Can't connect to premint.xyz

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#2985]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect to https://www.premint.xyz/

### What did not work?

Error: The user rejected the request

Could this be one that's solved with our impersonate MM registry?

<img width="430" alt="Screen Shot 2023-02-05 at 12 42 54" src="https://user-images.githubusercontent.com/71384922/216816700-a0e7c228-74e4-4c29-941d-6ff0745c6673.png">

### Version

v0.21.0

**Comment by jagodarybacka** [comment]
Seems like `personal_sign` params are flipped, first should be message then address
![image](https://user-images.githubusercontent.com/20949277/217003356-cac9df4a-030f-4f37-b6e3-1574b93cfe0c.png)
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-personal#personal-sign
