### ISSUE TITLE
Exclude testnets funds from Portfolio balance

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#2990]
Testnets funds shouldn't be included in calculating account balances across networks.

This is possible regression because I can't see this effect in the current version but I have this problem in my extension that was installed for some time.

**Comment by tallysam** [comment]
Can you please update this ticket to what version we see this behavior?

**Comment by jagodarybacka** [comment]
I've checked now and I can no longer reproduce this, maybe I did my calculation of how much funds I have on all networks incorrectly then 🤔 Let's close it
