### ISSUE TITLE
Support multiple simultaneous hardware wallets

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#3]
The entire legacy keyring deserves a rethink, but starting with fixing this inconvenience for DeFi prosumers and developers would go a long way.

**Comment by beemeeupnow** [comment]
funny that my unrelated PR to another fork shows here :sweat_smile: 

In any case, is this issue still relevant for modern code-base?
I know @Shadowfiend has recently looked at UI-side improvements for signers, but don't have a way to test the backend for Ledger myself.
