### ISSUE TITLE
`Need Help?` link is broken

### ISSUE THREAD

**Issue by 0xDaedalus** [tallyhowallet/extension#3040]
Current link - https://taho.notion.site/Tally-Ho-Knowledge-Base-4d95ed5439c64d6db3d3d27abf1fdae5 - takes users to a 404 page

**Comment by tallysam** [comment]
What version of the wallet is this for? I get taken to this address inside the wallet:

https://tallyhowallet.notion.site/Tally-Ho-Knowledge-Base-4d95ed5439c64d6db3d3d27abf1fdae5

**Comment by jagodarybacka** [comment]
that was on 0.25.x but we [changed it](https://github.com/tallyhowallet/extension/commit/c2fb3a26978bec095902a251a64edff7fe37b84b) and there is also a redirect so it's good to be closed
