### ISSUE TITLE
Choose which assets to display consistently

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#305]
Which assets should be shown, when?

* 0-balance assets are annoying most of the time, but if you had a balance and it recently became 0, it's nice to see a 0-balance asset
* Some users want to see small exact balances, others don't
* Every network has a base asset that should always show, even if they're 0
* We should *probably* show TALLY everwhere?

**Comment by 0xDaedalus** [comment]
Closed because:
- We have decided not to show 0 balance assets
- We have added a toggle that lets users see small exact balances
- We show the base asset of every network regardless of balance
