### ISSUE TITLE
integration test w/ jest 

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#329]
We need to be able to write integration tests easily so we can be sure our extension works so we can move fast with confidence

problems that need to have a good solution:
* [x] how to instantiate services separately // use the create() static method on the providers
* [x] 3rd party/external api call handling 
* [x] mocking time so it's possible to test timebased functionality 
* [x] indexdb usage in test environment 
* [x] mocking event between services

> do we mock, do we record and replay?

I say we mock for now and when we feel the pressure then we start thinking about more sophisticated solutions

https://jestjs.io/docs/manual-mocks
https://jestjs.io/docs/es6-class-mocks
https://jestjs.io/docs/bypassing-module-mocks

https://github.com/ikatyang/jest-playback
https://www.npmjs.com/package/@scaleleap/jest-polly?activeTab=readme

https://www.npmjs.com/package/fake-indexeddb
https://dev.to/andyhaskell/testing-your-indexeddb-code-with-jest-2o17

**Comment by 0xDaedalus** [comment]
The functionality described in this issue has been implemented 🎉
