### ISSUE TITLE
Move the all redux related code into a shared package

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#491]
The store is a cross cutting concern between our background and ui, becasue we are using [web-ext/redux](https://github.com/tshaddix/webext-redux)
At the moment the redux store and all the related types are defined in the background package, and the ui imports from there. 

As a result of this setup the whole background codebase is included in the ui bundle which creates  a significant size increase. (2+ mb)

If we were to put the store into a separate package only the used code would be bundled with the ui resulting in decrased bundle size and probably better perfomance and cleaner separation. 

The purpose of this ticket is to handle this separation. The goal is achieved 
- [ ] If all the redux related code (and types) are in a separate package
- [ ] UI and background is importing from this package using it's package name (and not path)
- [ ] The size of the UI bundle decreases
- [ ] We do not loose typing information (throughout the whole codebase)

‼️ This reafctor will cause breaking changes with every exising feature branch ‼️ 
Please communicate extensively when picking up this issue!

**Comment by 0xDaedalus** [comment]
Closed b/c this seems to be very high risk issue with a somewhat unclear upside.  We will probably need to revisit this when we decide to support firefox but as that is not in the roadmap for the next 12 months we can close this issue.
