### ISSUE TITLE
Transaction fail error

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#525]
Antonio 
>Sometimes the user is asked to sign a transaction that will almost certainly fail on-chain. This can happen, for example, if the dapp doesn’t properly check that it will succeed (eg trying to swap more than your balance on a swap dapp), if the gas limit is incorrect, or if the on-chain state has changed since the dapp checked the transaction (eg for swaps if there is no longer sufficient liquidity to execute the swap).

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/145225202-df2fc866-4b06-4b6d-a4a8-556d98b8e70a.png)

@Shadowfiend 
Can we be a bit specific? or do we have to go with a more general error for now?

**Comment by Shadowfiend** [comment]
We probably need to be more general right now, but we can def get more specific over time.

Is the idea that this covers up the Sign button?

**Comment by VladUXUI** [comment]
Yes, that is the idea. Because we don't want users to jump ahead and click the button without first knowing what is up.
But i'm open to thoughts on it being a good idea or not. I might have not thought around to all edge-cases

**Comment by 0xDaedalus** [comment]
Closed b/c we now warn about insufficient funds
