### ISSUE TITLE
Easier address access

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#553]
As a user, I'd like to be able to paste and view wallet addresses across the browser without opening the extension. 

To accomplish this, we should

- [ ] Include a [paste address keyboard shortcut](https://github.com/tallycash/extension/issues/551)
- [ ] Include wallet addresses [in right-click context menus](https://github.com/tallycash/extension/issues/552)

**Comment by mhluongo** [comment]
cc @VladUXUI to check this out, the sub issues have some interesting design and product questions

**Comment by 0xDaedalus** [comment]
Closed in favor of #551
