### ISSUE TITLE
Investigate performance + extension size impact of bundling + minification

### ISSUE THREAD

**Issue by Shadowfiend** [tallyhowallet/extension#56]
Since extensions are loaded locally rather than requiring network round-trips and bandwidth, I haven't been able to find strong evidence either way on whether bundling and minification provide a significant runtime impact. The downloaded extension itself is gzipped, so a lot of the file size improvement of minification _most likely_ already comes from that compression process.

The goal here is to understand:
- What the loading performance impact is of unminified code.
- What the loading performance impact is of unbundled code.
- What the loading performance impact is of bundled source maps, and whether browsers pick these up easily.
- What the extension size impact is of unminified code.
- What the extension size impact is of unbundled code.
- What the extension size impact is of bundled source maps.

These can then be synthesized with any other concerns to make a decision about the best way to move forward on minification and bundling.

## But Why?

One of the most developer-hostile things modern web technology does is obfuscate code. Source maps help, but require additional work and are often not included in production bundles. Tally being an open source project, we should encourage exploration and tinkering with the underlying source---the easiest way to do that is to give users and developers an already-usable code base with the shipped extension.

**Comment by 0xDaedalus** [comment]
Closed b/c stale - and this does not seem to currently be a concern of the project.
