### ISSUE TITLE
Different thousands and decimals separation signs

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#576]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/893564740427743292/919305602344296459

### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

-Token balance uses . for thousands and , for decimals. Total token $ value uses , for thousands and . for decimals
<img width="195" alt="Screenshot 2021-12-11 at 21 39 25" src="https://user-images.githubusercontent.com/71384922/145691014-bec99520-4d7a-48f0-bb40-05dd887e9748.png">

### What did not work?

See above

### Version

0.8.0

**Comment by Shadowfiend** [comment]
Hmmm. This will be an issue with the fact that the local formatting uses commas for decimals, but correct USD formatting uses periods. Need to see if we're missing a locale parameter, or if this is more complicated.

**Comment by Naxsun** [comment]
Tried to switch the separation sign locally on my macbook but that doesn't make a difference

**Comment by 0xDaedalus** [comment]
This is no longer an issue ✅
