### ISSUE TITLE
Loading icon images + prices for tokens is fairly slow

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#584]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

This is definitely not a blocker for CE release(!), but we should talk about whether there are ways to speed this up and/or smooth up the ux

- Took about 2 minutes for USD value of KEEP balance to appear
<img width="165" alt="Screen Shot 2021-12-11 at 5 02 46 PM" src="https://user-images.githubusercontent.com/7005061/145693746-15e1c861-582a-4313-aada-9bad3e522214.png">

- KEEP icon was blurry for about 20 mins (note time in screens)
 
<img width="656" alt="Screen Shot 2021-12-11 at 5 02 22 PM" src="https://user-images.githubusercontent.com/7005061/145693757-fd3f8499-7426-4acc-a9d1-ab789bc1ee6b.png">

<img width="833" alt="Screen Shot 2021-12-11 at 5 26 49 PM" src="https://user-images.githubusercontent.com/7005061/145693769-0af67fed-8e29-44f9-81d8-511c2b0084ad.png">

- Only other token that had this initial blurry pass was the graph

<img width="244" alt="Screen Shot 2021-12-11 at 5 07 42 PM" src="https://user-images.githubusercontent.com/7005061/145693781-86747c26-89ff-4276-ad12-750243b987b4.png">

- For other tokens ... took awhile for placeholder symbols and prices to appear 

<img width="359" alt="Screen Shot 2021-12-11 at 5 08 43 PM" src="https://user-images.githubusercontent.com/7005061/145693788-92914182-daaa-46f9-ac16-3b83b5f84fde.png">

<img width="146" alt="Screen Shot 2021-12-11 at 5 06 48 PM" src="https://user-images.githubusercontent.com/7005061/145693789-78fb685a-7b6c-43c6-9a5b-a99a3b4f04c5.png">

**Comment by 0xDaedalus** [comment]
This is no longer an issue ✅
