### ISSUE TITLE
Disperse.app txns don't appear in txn history

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#589]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Wanted to view the ETH and KEEP that had been sent to me for testing at https://etherscan.io/address/0x1cBb77B65B07403AD7f85Ff073bFC29a8212219c#internaltx via https://disperse.app/

### What did not work?

These txns aren't picked up by our txn history! Instead a perpetual loading state displays ...

<img width="358" alt="Screen Shot 2021-12-11 at 5 51 02 PM" src="https://user-images.githubusercontent.com/7005061/145694457-d1100d21-d090-4258-b624-3cdc9e9ea994.png">

<img width="340" alt="Screen Shot 2021-12-11 at 5 51 07 PM" src="https://user-images.githubusercontent.com/7005061/145694459-c8b0cff8-da21-4190-8061-10f090ebe44c.png">

**Comment by SJQuality** [comment]
I think https://disperse.app/ is gone now.. lol 
![image](https://user-images.githubusercontent.com/103908695/168388416-06fc5800-a271-4a59-8546-6bb639a7c3db.png)

@mr-michael can you repro... if it's even possible now?

**Comment by 0xDaedalus** [comment]
Closed b/c stale and no repro steps
