### ISSUE TITLE
Bitcoin support

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#6]
This is a big one.

A UTXO model breaks many assumptions in wallet land, including the idea of watching accounts for updates. There are a few major requirements

- [ ] A web3-style API for Bitcoin
- [ ] PSBT support, allowing more complex tx construction
- [ ] Message signing support
- [ ] More flexible chain data models to allow tracking single addresses (boo) or x/y/zpubs (yay)

**Comment by lightswarm124** [comment]
Might be worth looking into setting up a redux store to handle the UTXOs and key derivation

https://github.com/badger-cash/badger-mobile/tree/develop/data

**Comment by mhluongo** [comment]
Ooh great reference, thanks @lightswarm124! We'd probably keep the main UTXO store in IndexedDB, and only keep outputs relevant to the wallet in Redux.

Interested in any other thoughts you have around this!

**Comment by lightswarm124** [comment]
I'm still looking through the repo / documentation - haven't worked with IndexedDB personally but I know it's what most of the client implementations use to store the block data.

Not sure if it's going to be relevant for BTC but there is an UTXO-based token system on BCH called SimpleLedger Protocol (SLP). It involves writing OP_RETURN metadata and chaining UTXOs for validation.

https://simpleledger.cash/

**Comment by mhluongo** [comment]
Just supporting base UTXO send / receive and getting an in-page API is going to be a lot tbh. Once we're there + have an audit of the key stuff the sky is the limit.

**Comment by 0xDaedalus** [comment]
Closed b/c stale and not on roadmap for next 12 months.
