### ISSUE TITLE
Show all dApp connections in dropdown menu

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#605]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I connect to uniswap and then saddle. I click on the connections icon, I expect to see both saddle and uniswap as connections.

### What did not work?

... but I only see saddle as the connection! (Not shown in the video: when I head back to uniswap, it displays only uniswap as a connection)

https://user-images.githubusercontent.com/7005061/145882257-0a7565a9-ae35-447e-8286-c8f588d67004.mov

**Comment by henryboldi** [comment]
This is by design for this version.

**Comment by mhluongo** [comment]
A new design has been implemented as of #2118. We can flip the flag whenever @mr-michael

**Comment by 0xDaedalus** [comment]
Closed b/c outdated and new design has been implemented.
