### ISSUE TITLE
Preload token list icons when adding a new account

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#621]
When a new account is loaded and balances are checked, assets often show up before their metadata or even their images have been loaded.

We should either preload token list icons when adding a new account (eg using JS's `const img = new Image(); img.src = "..."`) or cache all token images local to the extension (good for privacy later) to prevent flickers

**Comment by creckhow** [comment]
<img width="142" alt="Screen Shot 2021-12-14 at 6 08 30 PM" src="https://user-images.githubusercontent.com/74791142/146104914-ca59f875-099e-4424-a9a5-1bcb8ce46d49.png">
I'm assuming this is what I was experiencing here...the Keep logo was low res fuzzy like this for the first ~30+ minutes after I imported my wallet. Ether logo looked fine, full res. A couple hours later the Keep logo loads properly.

**Comment by mhluongo** [comment]
Nope! What you've got there has another ticket, it's even more odd.

This issue is about a flicker from "no logo" to "logo"

**Comment by 0xDaedalus** [comment]
Closed in favor of https://github.com/tallyhowallet/extension/issues/408
