### ISSUE TITLE
Fail gracefully without gas price data

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#635]
![Screenshot from 2021-12-14 21-20-53](https://user-images.githubusercontent.com/427505/146111205-5acfe755-1de8-4b23-942b-eb0a3fd67909.png)

![Screenshot from 2021-12-14 21-20-59](https://user-images.githubusercontent.com/427505/146111212-551fe61a-0a24-4377-b571-bfd7948823ab.png)

Without gas price data, the send ETH page leads to signing a 0-fee transaction. No bueno.

Instead, the page should fall back to manual entry in the UI, and we should try to find dumber gas price data via the connected node.

**Comment by 0xDaedalus** [comment]
The entire gas experience is expected to have a revamp soon - closing because stale and we can address these types of issues as part of that work.
