### ISSUE TITLE
Display contract creation consistently on signing and activity pages 

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#648]
Contract deployment isn't very common in a browser extension wallet, but it's become more and more common with new use cases found for `CREATE2`. Let's design how we want contract deploys to look when signing transactions + showing them in the activity list.

Initially noticed this [here](https://github.com/tallycash/extension/pull/546#discussion_r769229018)

**Comment by 0xDaedalus** [comment]
Closing b/c not on the roadmap for the next 12 months
