### ISSUE TITLE
Shared address display component + copy button

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#649]
We display addresses all over the place. We should have shared address display components with copy buttons.

I'd propose
- [ ] one that doesn't include a copy button but still copies on click. This can even be styled like text... whatever is takes to fit our look and feel while making truncated addresses copyable.
- [ ] another the includes an actual button, as currently used on the Receive page.

Thoughts @VladUXUI @henryboldi? Here's where the discussion got started.

>  It's terrible. We probably want a component that does this + a copy button + a `title` with the full address.

_Originally posted by @Shadowfiend in https://github.com/tallycash/extension/pull/546#discussion_r769231648_

**Comment by VladUXUI** [comment]
We have a Ui component and a ux for this. Could potentially be rethought. 
Basically clicking on name/ens would copy the address + show a "address copied to clipboard" snackbar.

> We display addresses all over the place.
I'm uncertain if it's a good idea to let people copy from any/more places by clicking on an address. I think this could lead to people making mistakes and sending funds to wrong addresses. Having one or two source of truth from were you can copy an address might be safer. But definitely worth some exploration/testing.

![image](https://user-images.githubusercontent.com/80846886/146153082-d39968da-301b-4957-bf48-2402ee5a3d71.png)

I suspect we will soon need to show the address under the account name though(but first i want to test with just the name + show address on mouse over).

**Comment by Shadowfiend** [comment]
> one that doesn't include a copy button but still copies on click.

This is not great for accessibility and discoverability; I would def prefer to show an explicit button for it... And I don't think we're so tight for space anywhere that it would be a problem? I realize it makes for some extra line noise though.

**Comment by mhluongo** [comment]
Accessibility should be about an increase in functionality to serve more people IMO, not a decrease to some sort of lowest common denominator. I'm bringing up a button-less control because I'd rather make sure all our addresses are copy-able than make people go to EtherScan.

Maybe our designs solve this everywhere, but remember this will one day include tx call args, transfer recipients, etc.

**Comment by Shadowfiend** [comment]
🤔 I'm not suggesting we make things not copyable because of the button, right? Just that we should use a button unless we really can't.

**Comment by 0xDaedalus** [comment]
Closed as part of #1231
