### ISSUE TITLE
Uniswap - approval confusion

### ISSUE THREAD

**Issue by krisjpi** [tallyhowallet/extension#679]
dapp seems to be confused whether the wallet has approved a token for transfer. Sometimes skips to the swap button, but gives error "could not estimate gas for the swap" when swap is attempted.

The token has not yet been approved for trading on Uniswap in either screenshot. This could be a UNI issue as well.

![Uniswap Interface swap without approve](https://user-images.githubusercontent.com/41163644/146324164-1fcf770d-e05b-492b-a65c-1c4205990c74.png)
![Uniswap Interface](https://user-images.githubusercontent.com/41163644/146324151-7b42d03a-c9a9-4ba0-8537-e816e7bf2972.png)

**Comment by 0xDaedalus** [comment]
This seems to no longer be an issue ✅
