### ISSUE TITLE
Better ux/ui for TX details pages

### ISSUE THREAD

**Issue by VladUXUI** [tallyhowallet/extension#682]
Currently our transaction details page looks like this:
![image](https://user-images.githubusercontent.com/80846886/146332903-65ab9359-d636-460d-82da-5c811c49ab7b.png)

**Comment by VladUXUI** [comment]
There is plenty of room for improvements/explorations including:
- bundled transactions 
- better states for activity Log (broadcasting/pending/failed...
- different layouts for different types of transactions (swap/approve/contract interactions/stake...)

**Comment by 0xDaedalus** [comment]
While there is certainly still room for improvement here - closing b/c issue is stale and I am sure that this page will get some much needed attention in the upcoming design audit.
