### ISSUE TITLE
Keep Dashboard - Explorer Mode

### ISSUE THREAD

**Issue by krisjpi** [tallyhowallet/extension#697]
Tally connects to the Keep Dashboard and can generally navigate through the dash with Tally wallet info, but when moving through deposit flow (coverage pools here), generates warning about being in explorer mode and to connect wallet. This connect wallet button does not interact with Tally, but throws error 'window.ethereum provider not found' and prompts me to install MM.
![Connect Wallet - Keep Dash](https://user-images.githubusercontent.com/41163644/146448797-d493dfd1-032c-4352-9630-1cc8ae1fe522.png)
![Connection Error](https://user-images.githubusercontent.com/41163644/146448806-ca3ea3fd-f3b6-4730-884a-b78bf2e70305.png)

**Comment by 0xDaedalus** [comment]
Closing b/c stale
