### ISSUE TITLE
Alchemix dapp doesn't receive notice of tx confirmation

### ISSUE THREAD

**Issue by krisjpi** [tallyhowallet/extension#716]
I approved and staked tALCX on Alchemix. The transactions worked fine, but the dapp never received an update on the confirmation and continued to signal a pending tx.
![approval complete](https://user-images.githubusercontent.com/41163644/146490933-e520b12b-0c62-4e3b-885c-37df18f78b3b.png)
![staking complete](https://user-images.githubusercontent.com/41163644/146490937-9835c6d9-4c33-473a-9a90-8063a098b6ee.png)

**Comment by 0xDaedalus** [comment]
This seems to no longer be an issue ✅
