### ISSUE TITLE
Don't allow a transaction to be signed if an EVM address with mixed caps doesn't pass the checksum

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#774]
![Screenshot from 2021-12-29 11-13-08](https://user-images.githubusercontent.com/427505/147682245-f44d8dbd-4814-4d28-a779-6d0d57a2bd54.png)

Mixed-case hex addresses imply following [EIP-55](https://eips.ethereum.org/EIPS/eip-55), which can help prevent users from sending funds to the wrong address. If the address doesn't check out, the form shouldn't validate.

If an address is all lower-case or all upper-case, a warning should be displayed below the address input... maybe with a link to EtherScan to help users check what's up.

**Comment by mhluongo** [comment]
Note this goes for sending ETH, ERC-20s, and any transaction construction really... including if a dApp built the tx.

**Comment by SJQuality** [comment]
It looks like in this field we are only checking the length of the address, not actually validating if it's a legit address or not. Well, unless my taking a legit address and randomly changing characters is somehow always a legit address.

**Comment by 0xDaedalus** [comment]
While this is objectively good for security - while working on the RSK integration we've determined that this is not necessarily good for UX - since plenty of website (etherscan included) present users with and allow them to copy addresses that do not necessarily pass the checksum.
