### ISSUE TITLE
Update onboarding integration so it works as intended when tally is not set to be the default wallet

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#883]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/930169481660104725/933995725606498364

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

When using the tally integration on https://staking.synthetix.io/ and tally is not set to be a default wallet the integration is broken.

### What did not work?

Using the dedicated tally integration with tally not being the default.

### Version

Community Edition v0.10.2

**Comment by SJQuality** [comment]
Issue remains

**Comment by 0xDaedalus** [comment]
This is no longer an issue ✅
