### ISSUE TITLE
Test environment setup (Mainnet fork w/ hardhat)

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#885]
Where we can test e2e our extension and its integration with smart contracts. 

The plan: 
- [ ] register an alchemy archive node
- [ ] set up hardhat mainnet fork using said archive node https://hardhat.org/hardhat-network/guides/mainnet-forking.html
- [ ] implement (getBalance())[https://github.com/tallycash/extension/blob/main/background/lib/erc20.ts#L44] to use this archive node and wire it in (getBalances())[https://github.com/tallycash/extension/blob/main/background/lib/erc20.ts#L59]
- [ ] create an environment variable to turn this on or off

We might end up finishing the multichain support PR for this. https://github.com/tallycash/extension/pull/732

**Comment by 0xDaedalus** [comment]
Closed b/c outdated - although we do intend to revisit our e2e testing setup in the near future.
