### ISSUE TITLE
Push notifications on tx status

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#9]
We want browser push notifications on

- [ ] Tx submission
- [ ] Tx mempool drop
- [ ] Tx confirmation
- [ ] Payment receipt

To avoid running a centralized backend, we want to use a provider that supports WebSockets.

https://docs.blocknative.com/websocket

We also need to fall back gracefully, first to a regular data provider or local node, then to skipping the functionality.

**Comment by 0xDaedalus** [comment]
This has more-or-less been completed.  If we want to revisit or enhance our current implementation we can open a new issue for the work.
