### ISSUE TITLE
Seed gen - failure state missing design

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#906]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

If I enter the seed incorrectly, I get the following. It feels like something is missing here. As a user... it's confusing and not 100% clear what to do next.

<img width="365" alt="Screen Shot 2022-01-27 at 6 10 42 PM" src="https://user-images.githubusercontent.com/7005061/151459472-33032023-ab22-4b67-90b5-eb7fea0f45bd.png">

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/151500690-acedf196-d6d5-4cc6-a286-8c5a69df3395.png)
I propose we add more text until new design is implemented.

"Incorrect phrase order
Remove the words and try again, make sure you have the seed written down"

**Comment by SJQuality** [comment]
Issue remains

**Comment by 0xDaedalus** [comment]
This is no longer an issue
