### ISSUE TITLE
WalletConnect / external signer support

### ISSUE THREAD

**Issue by mhluongo** [tallyhowallet/extension#91]
As a precursor to more hardware wallet support, we plan to support [WalletConnect](https://walletconnect.org/) as an external signer.

This looks a little different than regular WalletConnect support (which we also need, less urgently).

Any user should be able to add a WalletConnect account to the extension. The extension should show balances, incoming transactions, etc the way it would for other accounts, and outsource transaction signing to the connected wallet.

**Comment by 0xDaedalus** [comment]
Closed in favor of https://github.com/tallyhowallet/extension/milestone/20
