### ISSUE TITLE
Wallet selection option missing

### ISSUE THREAD

**Issue by Naxsun** [tallyhowallet/extension#959]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/937878508439470130

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Add an additional wallet

### What did not work?

The user did not have the address / dog option in the top right. After creating a new profile in Brave, and re-installing Tally, it worked for this user.

![image](https://user-images.githubusercontent.com/71384922/153066849-3d5ad69b-5c99-4a30-891a-415eef9c8796.png)

![image](https://user-images.githubusercontent.com/71384922/153066863-d06a9eef-42c0-4ad7-89f7-d861da17c37a.png)

### Version

Community Edition v0.11.0

**Comment by 0xDaedalus** [comment]
This is no longer an issue
