### ISSUE TITLE
Swap selection panel missing ETH

### ISSUE THREAD

**Issue by henryboldi** [tallyhowallet/extension#977]
On the latest build w/ Swaps as of Feb 11,

<img width="379" alt="swap" src="https://user-images.githubusercontent.com/1918798/153689085-cab6d11f-bce5-4cdc-8e9f-666a52ba720d.png">

Fresh install using `0x208e94d5661a73360d9387d3ca169e5c130090cd`'s seed

**Comment by mhluongo** [comment]
ETH isn't supported until we launch our own contracts, only WETH/ERC-20s. We should better communicate this though

**Comment by cairomassimo** [comment]
Also, this is the UX if you don't have any token. Not pleasant. @VladUXUI we'll need a design for this I guess.
![Screenshot from 2022-02-24 14-45-08](https://user-images.githubusercontent.com/4115717/155526544-9e79d24f-dc1c-4c65-9d1d-a5853c7f5cd5.png)

**Comment by 0xDaedalus** [comment]
No longer an issue ✅
