### ISSUE TITLE
Add missing information bits on Ledger onboarding

### ISSUE THREAD

**Issue by fernya** [tallyhowallet/extension#985]
![Screenshot from 2022-02-09 14-23-05](https://user-images.githubusercontent.com/427505/153276234-da8c73d9-2469-42e1-8dc4-a32031239b5d.png)

This is what I see if I click "I don't see my device". Love the path on there, lol. Probably need to add something here or unlink that bit before prod though.

_Originally posted by @mhluongo in https://github.com/tallycash/extension/issues/965#issuecomment-1034119833_

**Comment by VladUXUI** [comment]
This is going to be a link for outside page. Either our FAQ or Ledger documentation.
Will get back to you when i have the information

**Comment by fernya** [comment]
Awesome, thanks! :)

**Comment by 0xDaedalus** [comment]
"I don't see my device" seems to no longer be an available option.
